- Makefile
- README.md
- subsystem/main_test.go
This PR adds a support running terraform against a local version of OCM provider
> fix the install command

- docs/resources/identity_provider.md
- examples/create_gitlab_identity_provider/README.md
- examples/create_gitlab_identity_provider/main.tf
- provider/identity_provider_resource.go
- provider/identity_provider_state.go
- subsystem/identity_provider_resource_test.go
Adding gitlab identity provider.
> Adding gitlab identity provider 

- README.md
- docs/index.md
Make terraform wait for creation/destroy in the doc.
> make terraform shell creation/deletion exit until the operation finished

- docs/resources/cluster_rosa_classic.md
Update aws_private_link description
> Update aws_private_link description

- docs/resources/cluster_rosa_classic.md
Update was generated by `tfplugindocs`.
> [SDA-8476] Update TF docs for cluster_rosa_classic

- docs/resources/cluster_rosa_classic.md
- provider/cluster_rosa_classic_resource.go
- provider/cluster_rosa_classic_state.go
- subsystem/cluster_resource_rosa_test.go
> [SDA-8476] Rename `compute_labels` -> `default_mp_labels`

- provider/identity_provider_resource.go
- provider/identity_provider_state.go
- provider/idps/mapping_method_validator.go
- subsystem/identity_provider_resource_test.go
Added mapping_method support.
- Validation
- idp create
- idp read
- subsytem tests
> OCM-201: Add support for mapping_method

- go.mod
- go.sum
- provider/cluster_rosa_classic_resource.go
- provider/cluster_rosa_classic_resource_test.go
- provider/cluster_rosa_classic_state.go
- subsystem/cluster_resource_rosa_test.go
[OCM-141](https://issues.redhat.com//browse/OCM-141): Changing parameter name from HttpTokensState to Ec2MetadataHttpTokens
> OCM-141: Changing parameter name from HttpTokensState to Ec2MetadataHttpTokens

- README.md
https://issues.redhat.com/browse/OCM-883
> Add instructions to README.md on how to get binary from image.

- ci/apply_folder.sh
- ci/destroy_folder.sh
- ci/setup_prow_env.sh
When running `make apply_folder` or `make desrtoy_folder` from PROW CI, save all tf files to artifacts.
> Store .tf files in artifact dir on PROW runs

- provider/cluster_rosa_classic_resource.go
> OCM-1026: Improve "Not supported version" error mesage

- examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/README.md
- examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/README.md
- examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/README.md
This PR updates the instructions for the highlighted examples:
* [Account Roles](https://github.com/terraform-redhat/terraform-provider-ocm/blob/3b992298d384a2eff40d789c9c9746b96266b727/examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/README.md)
* [Cluster with Managed OIDC](https://github.com/terraform-redhat/terraform-provider-ocm/blob/3b992298d384a2eff40d789c9c9746b96266b727/examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/README.md)
* [Cluster with Unmanaged OIDC](https://github.com/terraform-redhat/terraform-provider-ocm/blob/3b992298d384a2eff40d789c9c9746b96266b727/examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/README.md)
> Update example docs

- docs/resources/identity_provider.md
- provider/common/helpers.go
- provider/identity_provider_resource.go
- provider/idps/ldap.go
- subsystem/identity_provider_resource_test.go
- Updated schema
- Added validations
- added default values for ldap.attributes
- Updated related docs
On the way, fixed some indentations and typos found.
:warning: **REVIEWERS**: Please validate and double-check my regex for email validation.
> OCM-2420: LDAP IDP fixes

- examples/create_identity_provider/ldap/README.md
- examples/create_identity_provider/ldap/main.tf
- examples/create_identity_provider/ldap/terraform.tfvars
> OCM-2342: Adding IDP examples and docs phase 2

- README.md
- docs/index.md
- docs/modify-cluster.md
- docs/terraform-vars.md
- examples/create_identity_provider/github/README.md
- examples/create_identity_provider/gitlab/README.md
- examples/create_identity_provider/google/README.md
- examples/create_identity_provider/htpasswd/README.md
- examples/create_identity_provider/ldap/README.md
- examples/create_machine_pool/README.md
- examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/README.md
- examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/README.md
This PR is a continuation of #122 that documents modifying the machine pools and creating your Terraform.tfvars.
* Addressed [OCM-2458](https://issues.redhat.com/browse/OCM-2458) with the following:
* Attempted to fix the broken list from Terraform Registry:
* Addressed [OCM-2463](https://issues.redhat.com/browse/OCM-2463)
**README.md**
**docs/index.md**
> Created new topics on Terraform vars and modifying machine pools.

- README.md
- docs/index.md
- docs/upgrading-cluster.md
- examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/main.tf
- examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
Created documentation for upgrading your cluster. I also added a new variable for the acknowledgment gates.
> Creating upgrading documentation

- README.md
- docs/index.md
To address [OCM-2496](https://issues.redhat.com/browse/OCM-2496), I added a list of limitations for OCM Terraform provider along with an updated list of policies.
This PR also covers [OCM-2494](https://issues.redhat.com/browse/OCM-2494):
> Updated README and Index for limitations and policies.

- provider/machine_pool_resource.go
- subsystem/machine_pool_resource_test.go
* Refactor the code, to make it more clear
* Populate state should set useSpotInstances only if it true, otherwise leave it empty
* Prevent setting negative "max_spot_price"
> OCM-2489: Fix useSpotInstances attribute usage

- ci/e2e/account_roles_files/main.tf
- ci/e2e/oidc_configuration/cluster_with_managed_oidc_config/main.tf
- ci/e2e/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
- examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/main.tf
- examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf
ref:
https://github.com/terraform-redhat/terraform-aws-rosa-sts/tree/v0.0.9
> CI: Updated module version 0.0.8 -> 0.0.9

- examples/create_ccs_cluster/main.tf
- examples/create_identity_provider/github/main.tf
- examples/create_identity_provider/gitlab/main.tf
- examples/create_identity_provider/google/main.tf
- examples/create_identity_provider/htpasswd/main.tf
- examples/create_identity_provider/ldap/main.tf
- examples/create_machine_pool/main.tf
- examples/create_machine_pool/variables.tf
- examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/main.tf
- examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/variables.tf
- examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/main.tf
- examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/variables.tf
- examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/main.tf
- examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
- examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
- examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/variables.tf
- examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf
- examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/variables.tf
- examples/list_cloud_providers/main.tf
- examples/list_machine_types/main.tf
- examples/list_versions/main.tf
Updated in examples:
- cleanup
- defaults
- versions
> Examples: Updated to the upcoming 1.0.5 release

- README.md
- examples/create_identity_provider/github/README.md
- examples/create_identity_provider/gitlab/README.md
- examples/create_identity_provider/google/README.md
- examples/create_identity_provider/htpasswd/README.md
- examples/create_machine_pool/README.md
- examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/README.md
- examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/README.md
- examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/README.md
> fixing some specifics in the readme #134

- CHANGELOG.md
See the file CHANGELOG for details.
> Release 1.0.5

- provider/cluster_rosa_classic_resource.go
- subsystem/cluster_resource_rosa_test.go
- Error if the requested version set to a value < current cluster version
- Cancel pending upgrades if requested version is set to current version
> OCM-2501: OCM-2512: Improve upgrade semantics

- docs/guides/machine-pool.md
- docs/guides/terraform-vars.md
- docs/guides/upgrading-cluster.md
* Move all guide files to "guides" directory
* Add "page_title" and "description" to each file
> OCM-2595: fix guides files publish to registry

- docs/index.md
* Single AZ NodePool not supported
* Resources deletion not from tf not supported
> Add open issues to docs

- CHANGELOG.md
- docs/index.md
- examples/create_ccs_cluster/main.tf
- examples/create_identity_provider/github/main.tf
- examples/create_identity_provider/gitlab/main.tf
- examples/create_identity_provider/google/main.tf
- examples/create_identity_provider/htpasswd/main.tf
- examples/create_identity_provider/ldap/main.tf
- examples/create_machine_pool/main.tf
- examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/main.tf
- examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/main.tf
- examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/main.tf
- examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
- examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf
- examples/list_cloud_providers/main.tf
- examples/list_machine_types/main.tf
- examples/list_versions/main.tf
* Change example links
* Add changelog
> Prepare release 1.1.0

- examples/create_machine_pool/variables.tf
Fixed a space indentation issue.
> Fix space indentation

- provider/identity_provider_resource.go
- subsystem/identity_provider_resource_test.go
This PR adds the ability to reconcile an IDP that was created by TF, but then was removed via a different method, Not via terraform.
In this case, And if the user still has the idp resource in his .tf (and state) files. Upon an apply the provider will re-create the idp.
Before this PR, the provider would have error out, since it could not find the idp defined in the state.
On the way, fixed indentation issues in the related subsystem
> OCM-2646: Recreate IDP if it was deleted not from tf

- provider/machine_pool_resource.go
- subsystem/machine_pool_resource_test.go
This PR adds the ability to reconcile a machine pool that was created by TF, but then was removed via a different method, Not via terraform.
In this case, And if the user still has the machine pool resource in his `.tf` files. Upon an `apply` the provider will re-create the pool. 
Before this PR, the provider would have error out, since it could not find the machine pool defined in the state.
> OCM-2644: Recreate machine pool if it was deleted from other client.

- tests/OWNERS
- tests/README.md
- tests/e2e/cluster_creation.go
- tests/e2e/init_test.go
- tests/prow_ci.sh
- tests/tf-manifests/aws/account-roles/main.tf
- tests/tf-manifests/aws/account-roles/variables.tf
- tests/tf-manifests/aws/vpc/main.tf
- tests/tf-manifests/aws/vpc/output.tf
- tests/tf-manifests/aws/vpc/variables.tf
- tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
- tests/tf-manifests/rhcs/clusters/rosa-classic/output.tf
- tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
- tests/tf-manifests/rhcs/idps/github/main.tf
- tests/tf-manifests/rhcs/idps/github/variables.tf
- tests/tf-manifests/rhcs/idps/gitlab/main.tf
- tests/tf-manifests/rhcs/idps/gitlab/variables.tf
- tests/tf-manifests/rhcs/idps/google/main.tf
- tests/tf-manifests/rhcs/idps/google/variables.tf
- tests/tf-manifests/rhcs/idps/htpasswd/main.tf
- tests/tf-manifests/rhcs/idps/htpasswd/variables.tf
- tests/tf-manifests/rhcs/idps/ldap/main.tf
- tests/tf-manifests/rhcs/idps/ldap/variables.tf
- tests/tf-manifests/rhcs/idps/openid/main.tf
- tests/tf-manifests/rhcs/idps/openid/variables.tf
- tests/tf-manifests/rhcs/machine-pools/main.tf
- tests/tf-manifests/rhcs/machine-pools/output.tf
- tests/tf-manifests/rhcs/machine-pools/variable.tf
- tests/utils/constants/constants.go
- tests/utils/helper/helper.go
Finished the tests structure folders creation. May enhance in future.
> Finish tests structure folders creation

- docs/index.md
> Fix a minor typo on docs index.md

- docs/index.md
> Prepare release v1.2.0-prerelease.1

- examples/create_identity_provider/github/main.tf
- examples/create_identity_provider/github/variables.tf
Could not find the cause of the array not being passed to terraform. 
This PR will simply make the example work.
> OCM-2670: Fix GitHub IDP example

- README.md
- docs/guides/upgrading-cluster.md
- docs/index.md
- examples/create_account_roles/README.md
- examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/README.md
- examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/README.md
* Added the IMDS variable to the cluster creation examples.
* Addressed [OSDOCS-6087](https://issues.redhat.com//browse/OSDOCS-6087)
* Addressed [OCM-2815](https://issues.redhat.com/browse/OCM-2815) where the secret was concealed
* Addressed [OCM-2626](https://issues.redhat.com/browse/OCM-2626)
* Addressed [OCM-2977](https://issues.redhat.com/browse/OCM-2977) to fix a broken link
> Various Terraform updates

- CHANGELOG.md
- docs/index.md
* Change example links
* Update the CHANGELOG file
> Release 1.2.0

- CHANGELOG.md
- docs/guides/machine-pool.md
- docs/guides/upgrading-cluster.md
- examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
- examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/variables.tf
Fixing the links to github
Fixing the default value of openshift_version to be empty
> V1.2.1 fix

- subsystem/identity_provider_resource_test.go
was missing from https://github.com/terraform-redhat/terraform-provider-rhcs/pull/230
> OCM-2637: Fix to subsystem tests of htpasswd

- tests/ci/profile_handler.go
- tests/e2e/cleaner.go
- tests/e2e/cluster_creation.go
- tests/e2e/init_test.go
- tests/e2e/machine_pool_test.go
- tests/tf-manifests/aws/account-roles/main.tf
- tests/tf-manifests/aws/vpc/main.tf
- tests/tf-manifests/aws/vpc/variables.tf
- tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
- tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
- tests/utils/constants/constants.go
- tests/utils/constants/profile_defaults.go
- tests/utils/exec/account-roles.go
- tests/utils/exec/cluster.go
- tests/utils/exec/machine-pools.go
- tests/utils/exec/tf-exec.go
- tests/utils/exec/vpc.go
- tests/utils/helper/helper.go
@nirarg @amalykhi @yasun1 Can you please review? It's just step 1. And I prefer it can be merged to unblock others.
> Step 1 of build up profile handler for testing CI

- tests/ci/profile_handler.go
- tests/e2e/cluster_creation.go
- tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
- tests/utils/exec/account-roles.go
- tests/utils/exec/cluster.go
- tests/utils/exec/machine-pools.go
- tests/utils/exec/tf-exec.go
- tests/utils/exec/vpc.go
It enhanced the args combine functions
And it enhanced the resource creations to services
It resolved some issues of the not updated manifests file
The un-used functions of createMyTFxxx will be removed in next PR
> profile handler step 2 -- enhance the command run to a service object

- CHANGELOG.md
- provider/cluster_rosa_classic_resource.go
- subsystem/cluster_resource_rosa_test.go
Fixing a case of updating the proxy attribute this the first time it was set (and it's null)
> OCM-3102: Ocm 3102 main

- provider/rosa_oidc_config_resource.go
[OCM-2720](https://issues.redhat.com//browse/OCM-2720): rosa_oidc_config tf resource: Recreate resource if it was deleted not from tf
tested manually by deleting cluster then deleting oidc-provider and running terraform apply, everything was recreated
> OCM-2720: rosa_oidc_config tf resource: Recreate resource if it was deleted not from tf

- build/ci-tf-e2e.Dockerfile
- build/info.go
- ci/apply_folder.sh
- ci/e2e/terraform_provider_ocm_fullcycle_test.go
- internal/rhcs/cloudprovider/cloud_providers_state.go
- internal/rhcs/cluster/clusterschema/cluster_schema.go
- internal/rhcs/idps/gitlab.go
- internal/rhcs/idps/identity_provider_resource.go
- internal/rhcs/idps/identity_provider_state.go
- internal/rhcs/machinetypes/machine_types_state.go
- internal/rhcs/provider/provider.go
- internal/rhcs/rolesandpolicies/rosa_operator_roles_data_source.go
- logging/logging.go
- main.go
- scripts/run_make_e2e_test.py
- subsystem/cluster_resource_rosa_test.go
- subsystem/group_membership_resource_test.go
- subsystem/identity_provider_resource_test.go
- subsystem/init_test.go
- subsystem/machine_pool_resource_test.go
- tests/README.md
- tests/utils/constants/constants.go
* reverting ``cprovider -> provider``
* reverting ``clusterservice -> provider``
> Fix bad text replacements

- docs/index.md
- examples/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
[OCM-3521](https://issues.redhat.com/browse/OCM-3521)
> minimal permission update

- provider/cloudprovider/cloud_providers_data_source.go
- provider/clusterwaiter/cluster_waiter_resource.go
- provider/dnsdomain/dns_domain_resource.go
- provider/provider.go
- cloud_provider_datasource
- cluster_waiter_resource
- dns_domain_resource
> Remove the schema import aliases and simplify to New()

- oldprovider/idps/htpasswd.go
- provider/clusterrosaclassic/admin_creds_validator.go
- provider/clusterrosaclassic/properties_validator.go
- provider/clusterrosaclassic/proxy_validator.go
- provider/clusterrosaclassic/sts.go
- provider/clusterwaiter/cluster_waiter_resource.go
- provider/common/attribute_validator.go
- provider/common/helpers.go
- provider/common/helpers_test.go
- provider/common/tfconversions.go
- provider/common/validators.go
1. Added validators ( admin_creds, properties, proxy )- to share the concept
2. Update the common with common functionality 
The common tests are passing
> Common changes and added validators

- internal/rhcs/machinetypes/machine_types_data_source.go
- Add error handling to machineTypesDSRead
> SDKv2: Fixup of machine types data source

- provider/common/helpers.go
- provider/oidcconfig/rosa_oidc_config_resource.go
- provider/oidcconfig/rosa_oidc_config_state.go
- provider/provider.go
Moving oidc_config to new framework
subsystem passes
> Moving oidc_config to new framework

- provider/common/helpers.go
- provider/common/tfconversions.go
- provider/machinepool/machine_pool_resource.go
- provider/machinepool/machine_pool_state.go
- provider/provider.go
- subsystem/machine_pool_resource_test.go
> Migrate machine_pool resource

- provider/cluster/cluster_resource.go
- provider/cluster/cluster_resource_test.go
- provider/cluster/cluster_state.go
- provider/clusterrosaclassic/cluster_rosa_classic_resource.go
- provider/clusterrosaclassic/cluster_rosa_classic_resource_test.go
- provider/clusterrosaclassic/cluster_rosa_classic_state.go
- provider/provider.go
- provider/proxy/proxy_resource.go
- provider/proxy/proxy_state.go
- provider/proxy/proxy_validator.go
Moving cluster to new framework part
In order to see diff please look on second commit
> Moving cluster to new framework part

- provider/cluster/cluster_resource.go
- provider/clusterrosaclassic/cluster_rosa_classic_resource.go
- subsystem/cluster_resource_rosa_test.go
- subsystem/cluster_resource_test.go
Availability zones should be computed field as there is default value in OCM
> Availability zones should be computed field as there is default value in OCM

- provider/identityprovider/google.go
Noticed this one when I was trying to figure out how to configure the Google IDP. Looks like a search/replace error during the FW upgrade
> Fix isNull -> isUnknown in google idp

- docs/index.md
- provider/provider.go
* Remove unused attributes
* Remove all attributes but Token from the docs - internal attributes
* Add option for environment variables for all string attributes
* Add "Authentication and configuration" section in the main index and remove attributes section
> OCM-4021: Provider Attributes changes

- docs/data-sources/machine_types.md
- docs/data-sources/policies.md
- docs/data-sources/rosa_operator_roles.md
- docs/resources/cluster_rosa_classic.md
- docs/resources/cluster_wait.md
- docs/resources/identity_provider.md
- docs/resources/machine_pool.md
- docs/resources/rosa_oidc_config.md
- docs/resources/rosa_oidc_config_input.md
- provider/clusterrosaclassic/cluster_rosa_classic_resource.go
- provider/clusterrosaclassic/sts.go
- provider/clusterwaiter/cluster_waiter_resource.go
- provider/identityprovider/github.go
- provider/identityprovider/identity_provider_resource.go
- provider/machine_types/machine_types_data_source.go
- provider/machinepool/machine_pool_resource.go
- provider/ocm_policies/ocm_policies_data_source.go
- provider/oidcconfig/rosa_oidc_config_resource.go
- provider/oidcconfiginput/rosa_oidc_config_input_resource.go
- provider/rosa_operator_roles/rosa_operator_roles_data_source.go
This is a cleanup of the changes in #332 from @arendej
> Changes from Aren

- examples/create_account_roles/main.tf
- tests/ci/labels.go
- tests/e2e/machine_pool_test.go
- tests/tf-manifests/rhcs/machine-pools/main.tf
- tests/tf-manifests/rhcs/machine-pools/output.tf
- tests/tf-manifests/rhcs/machine-pools/variable.tf
- tests/utils/cms/cms.go
- tests/utils/exec/machine-pools.go
Auto test case for https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-64905
Please, review @nirarg @sagidayan @tshefi @shellymiron
> machinepool label test

- tests/e2e/machine_pool_test.go
- tests/tf-manifests/rhcs/machine-pools/main.tf
- tests/utils/constants/constants.go
Automation of Polarion TC https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-64905
and
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-64904
The tests succeeded on local
Ran 4 of 8 Specs in 39.001 seconds
SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 4 Skipped
> taints and labels machinepool test

- tests/e2e/machine_pool_test.go
Adding TC: OCP-68283 Check the validations for the machinepool creation rosa clusters
The test passed
Ran 1 of 10 Specs in 13.785 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 9 Skipped
PASS
> machinepool validations

- .vscode/settings.json
- provider/common/helpers.go
- provider/identityprovider/ldap.go
- subsystem/identity_provider_resource_test.go
PR in relationship to this issue:
https://github.com/terraform-redhat/terraform-provider-rhcs/issues/341
Just removed the validation since I don't believe it is correct.
Removed the test that was "testing" the validation of the email key. 
And modified some of the other test values so they are closer to expected values.
> Updating email key validation

- tests/e2e/idps_test.go
- tests/tf-manifests/rhcs/idps/github/variables.tf
add --insecure-skip-tls-verify flag to tests with login
> add --insecure-skip-tls-verify flag to tests with login

- tests/ci/profiles/tf_cluster_profile.yml
- tests/e2e/idps_test.go
- tests/tf-manifests/rhcs/idps/github/main.tf
- tests/tf-manifests/rhcs/idps/github/output.tf
- tests/tf-manifests/rhcs/idps/github/variables.tf
- tests/tf-manifests/rhcs/idps/gitlab/output.tf
- tests/utils/constants/constants.go
- tests/utils/exec/idps.go
Adding gitlab/hub idp tests and set prod as default Gateway.
> adding gitlab/hub idp tests + fixes

- tests/e2e/machine_pool_test.go
- tests/tf-manifests/rhcs/machine-pools/main.tf
- tests/tf-manifests/rhcs/machine-pools/variable.tf
- tests/utils/exec/machine-pools.go
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-65063
terraform-provider-rhcs % ginkgo run --label-filter feature-machinepool  ./tests/e2e
......
an 6 of 17 Specs in 60.612 seconds
SUCCESS! -- 6 Passed | 0 Failed | 0 Pending | 11 Skipped
PASS
> Add  TC OCP-65063 Create single-az machinepool for multi-az cluster

- tests/e2e/idps_test.go
- tests/tf-manifests/rhcs/idps/google/main.tf
- tests/tf-manifests/rhcs/idps/google/variables.tf
- tests/utils/constants/constants.go
- tests/utils/exec/idps.go
> add google idp test case and additional fixes

- provider/clusterrosaclassic/validators.go
After this PR would be merged we should tag a new release version v1.4.1
> Fix a typo in error message of private_hosted_zone validator

- tests/ci/profile_handler.go
- tests/ci/profiles/tf_cluster_profile.yml
- tests/e2e/machine_pool_test.go
- tests/e2e/verfication_post_day1_test.go
- tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
- tests/utils/constants/constants.go
- tests/utils/exec/cluster.go
ALl post-day1 cases passed
Ran 6 of 20 Specs in 3.800 seconds
SUCCESS! -- 6 Passed | 0 Failed | 0 Pending | 14 Skipped
PASS
Ginkgo ran 1 suite in 6.471146834s
All machinepool cases passed
Ran 5 of 20 Specs in 48.230 seconds
SUCCESS! -- 5 Passed | 0 Failed | 0 Pending | 15 Skipped
PASS
> support singleaz private profile

- tests/ci/profile_handler.go
- tests/e2e/verfication_post_day1_test.go
- tests/utils/constants/constants.go
- tests/utils/helper/helper.go
additional post day 1 test cases: [OCP-63777](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-63777) & [OCP-63134](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-63134)
> automate OCP-63777 & OCP-63134

- CHANGELOG.md
> Release v1.4.1

- tests/ci/profile_handler.go
- tests/ci/profiles/tf_cluster_profile.yml
ginkgo run --label-filter day1-prepare --timeout 2h --output-dir /tmp --junit-report result.xml -r --focus-file tests/e2e/. tests/e2e/..
time="2023-11-16T12:18:39+02:00" level=info msg="Running against env staging with gateway url https://api.stage.openshift.com"
time="2023-11-16T12:18:39+02:00" level=info msg="Loaded cluster profile configuration from profile rosa-sts-pl : map[autoscale:false byok:false byovpc:true ccs:true channel_group:candidate cloud_provider:aws compute_machine_type:m5.xlarge etcd_encryption:false fips:false hypershift:false imdsv2:optional labeling:false major_version:4.14 multi_az:false oidc_config:managed private:true private_link:true product_id:rosa proxy:false region:us-east-1 sts:true tagging:false version:latest zones:]"
Running Suite: e2e tests suite - …
> Support major version for TR

- tests/e2e/idps_test.go
Related to this [thread](https://redhat-internal.slack.com/archives/C056164CVMX/p1700467534050719)
> small fix to add private_link condition to avoid login command for idps

- tests/ci/profile_handler.go
- tests/ci/profiles/tf_cluster_profile.yml
- tests/e2e/machine_pool_test.go
- tests/e2e/verfication_post_day1_test.go
- tests/tf-manifests/aws/security-groups/main.tf
- tests/tf-manifests/aws/security-groups/output.tf
- tests/tf-manifests/aws/security-groups/variables.tf
- tests/tf-manifests/aws/vpc/main.tf
- tests/tf-manifests/aws/vpc/output.tf
- tests/tf-manifests/aws/vpc/variables.tf
- tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
- tests/tf-manifests/rhcs/clusters/rosa-classic/output.tf
- tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
- tests/tf-manifests/rhcs/machine-pools/main.tf
- tests/tf-manifests/rhcs/machine-pools/variable.tf
- tests/utils/constants/constants.go
- tests/utils/exec/cluster.go
- tests/utils/exec/machine-pools.go
- tests/utils/exec/security-groups.go
- tests/utils/exec/tf-exec.go
- tests/utils/exec/vpc.go
- tests/utils/helper/helper.go
What I have done in this PR:
- Automated OCP-69145 @OCP-69146 @OCP-69144 OCP-69143 
> - for disk size day1 and day2
> - for security groups day1 and day2
> - Introduced plan command for some of the testing
> - Introduced apply command. Need to update others in future
> Automated OCP-69145 @OCP-69146 @OCP-69144 OCP-69143

- tests/e2e/general_day_two_test.go
- tests/tf-manifests/rhcs/dns/main.tf
- tests/tf-manifests/rhcs/dns/output.tf
- tests/tf-manifests/rhcs/dns/variable.tf
- tests/tf-manifests/rhcs/rhcs-info/main.tf
- tests/tf-manifests/rhcs/rhcs-info/variable.tf
- tests/utils/cms/cms.go
- tests/utils/constants/constants.go
- tests/utils/exec/dns-domain.go
- tests/utils/exec/import.go
- tests/utils/exec/rhcs-info.go
- tests/utils/exec/tf-exec.go
- tests/utils/helper/helper.go
simple and short test to validate test case [OCP-67570](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-67570) & [OCP-68301](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-68301)
**OCP-68301:**
**OCP-67570:**
> add dns-domain resource & rhcs-info tf data methods and tests

- provider/clusterrosaclassic/cluster_rosa_classic_resource.go
Cherry pick from main PR https://github.com/terraform-redhat/terraform-provider-rhcs/pull/427
> OCM-4621: avoid adding proxy to builder in case all values are empty

- provider/cluster/cluster_resource.go
- provider/clusterrosaclassic/cluster_rosa_classic_resource.go
Related issue: [OCM-5233](https://issues.redhat.com//browse/OCM-5233)
> OCM-5233 | fix: remove compute SGs from state

- .gitignore
- go.mod
- go.sum
- tests/README.md
- tests/ci/profile_handler.go
- tests/e2e/idps_test.go
- tests/e2e/machine_pool_test.go
- tests/utils/constants/constants.go
- tests/utils/constants/profile_defaults.go
- tests/utils/exec/account-roles.go
- tests/utils/exec/cluster.go
- tests/utils/exec/dns-domain.go
- tests/utils/exec/idps.go
- tests/utils/exec/machine-pools.go
- tests/utils/exec/oidc-provider-operator-roles.go
- tests/utils/exec/rhcs-info.go
- tests/utils/exec/security-groups.go
- tests/utils/exec/tf-exec.go
- tests/utils/exec/vpc-tags.go
- tests/utils/exec/vpc.go
- tests/utils/helper/file.go
What I did in the PR:
- Make cluster creation record the tfvars
- Updated README.md
- Moved `Create` to `Apply` to avoid confusion
- Changed part of attributes to use pointer
- Exclude some cases may unstable, will do enhancement in next PR
@amalykhi @shellymiron @yuwang-RH @nirarg could you please review?
> CI enhancement - step1 make tfvars can be recorded

- tests/e2e/cluster_creation_test.go
- tests/utils/constants/constants.go
- tests/utils/openshift/console.go
Ran 1 of 29 Specs in 4992.300 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 28 Skipped
PASS
Ginkgo ran 1 suite in 1h23m13.102341993s
> Operators check before running postday1 and day2 checks

- tests/e2e/idps_test.go
- tests/tf-manifests/rhcs/idps/multi-idp/main.tf
- tests/tf-manifests/rhcs/idps/multi-idp/variables.tf
- tests/utils/cms/cms.go
- tests/utils/constants/constants.go
**Test cases:** 
* https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-64030
* https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-66408
_note_ - both of the tests are using oc login. when testing locally sometimes the tests passed and sometimes not,
this is something that still needs to be investigated in the future.
> automating multiple idp applying scenarios

- subsystem/cluster_autoscaler_resource_test.go
Remove `skip_nodes_with_local_storage` and setting it to null
> OCM-5016: Add an update test to autoscaler resource

- provider/clusterautoscaler/cluster_autoscaler_resource.go
- provider/clusterautoscaler/validators.go
- subsystem/cluster_autoscaler_resource_test.go
The following attribiues are included here:
* log_verbosity
* core min
* memory min
* gpu min
> OCM-5017: Autoscaler resource - Add validation for not negative values

- tests/e2e/idps_test.go
Added empty username/password to the map to fix failing steps
> fix ocp-68939

- tests/ci/labels.go
- tests/e2e/negative_day_one_test.go
- tests/utils/constants/profile_defaults.go
Ran 2 of 48 Specs in 351.146 seconds
SUCCESS! -- 2 Passed | 0 Failed | 1 Pending | 45 Skipped
PASS
Ginkgo ran 1 suite in 5m52.245248251s
> OCM-4492: add day1 admin negative cluster

- provider/clusterrosaclassic/cluster_rosa_classic_resource.go
- provider/machinepool/machine_pool_resource.go
- subsystem/machine_pool_resource_test.go
> OCM-5407: Validate Immutable attributes not changed after magic import

- tests/e2e/negative_day_one_test.go
- tests/utils/helper/helper.go
the test failed: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/47096/rehearse-47096-periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-negative-f7/1740015404627005440
> fix random string function - the length was incorrect

- docs/guides/worker-machine-pool.md
- templates/guides/worker-machine-pool.md.tmpl
> NO-ISSUE: Adding a note about updating magic import's attributes

- tests/e2e/machine_pool_test.go
- tests/tf-manifests/rhcs/resource-import/main.tf
- tests/utils/exec/import.go
- tests/utils/exec/tf-exec.go
Based on this test case: https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-66403
> Add terraform-import machinepool test case 

- CHANGELOG.md
- docs/guides/machine-pool.md
- docs/guides/upgrading-cluster.md
- docs/index.md
- templates/guides/machine-pool.md.tmpl
- templates/guides/upgrading-cluster.md.tmpl
- templates/index.md.tmpl
1. Update Changelog
2. Change Examples links to use v1.5.0 tag
> V1.5.0 release changes

- tests/e2e/idps_test.go
- tests/tf-manifests/rhcs/idps/ldap/output.tf
- tests/utils/cms/cms.go
**OCP-65808:** 
**OCP-65814:**
**OCP-65816:**
> automate idp reconciliation scenrios

- .tekton/terraform-provider-rhcs-push.yaml
Adds YAML file that triggers the tasks for the release generation.
> OCM-2620 | ci: Add pipelinerun file for Konflux

- tests/e2e/verfication_post_day1_test.go
[OCM-5833](https://issues.redhat.com//browse/OCM-5833) | ci: update OCP-63334 test
> OCM-5833 | ci: update OCP-63334 test

- tests/e2e/machine_pool_test.go
[OCM-5833](https://issues.redhat.com//browse/OCM-5833) | ci: update OCP-64904 OCP-68283 test
> OCM-5833 | ci: update OCP-64904 OCP-68283  test

- .github/workflows/check-commit-format.yml
Fix github user name: red-hat-konflux --> red-hat-konflux[bot]
**Which issue(s) this PR fixes**:
Fixes #[OCM-5853](https://issues.redhat.com//browse/OCM-5853)
**Checklist**
> OCM-5853: Fix github user name: red-hat-konflux --> red-hat-konflux[bot]

- .github/workflows/check-commit-format.yml
- .tekton/terraform-provider-rhcs-push.yaml
> Rebase main

- go.mod
- go.sum
- tests/ci/labels.go
- tests/ci/profile_handler.go
- tests/ci/profiles/tf_cluster_profile.yml
- tests/e2e/cluster_creation_test.go
- tests/e2e/cluster_upgrade_test.go
- tests/e2e/general_day_two_test.go
- tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
- tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
- tests/utils/cms/cms.go
- tests/utils/constants/constants.go
- tests/utils/exec/cluster.go
- tests/utils/exec/tf-exec.go
- tests/utils/openshift/console.go
- tests/utils/openshift/openshift.go
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-63153
Test results:
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-63152
> OCM-5627 | ci: upgrade scenario test cases

- .github/workflows/check-commit-format.yml
> OCM-5853 | ci: Add "dependabot[bot]" to skip commit validations list

- tests/ci/profile_handler.go
- tests/ci/profiles/tf_cluster_profile.yml
- tests/e2e/cluster_upgrade_test.go
- tests/utils/cms/versions.go
both scenarios succeeded on local
> OCM-5627 |ci: upgrade fix

- provider/clusterautoscaler/cluster_autoscaler_resource.go
- provider/clusterrosaclassic/cluster_rosa_classic_resource.go
- provider/clusterwaiter/cluster_waiter_resource.go
- provider/common/cluster_waiter.go
- provider/common/mock_clusterwait.go
- provider/defaultingress/ingress.go
- provider/groupmembership/group_membership_resource.go
- provider/kubeletconfig/kubeletconfig_resource.go
- provider/kubeletconfig/kubeletconfig_resource_test.go
- provider/machinepool/machine_pool_resource.go
- subsystem/cluster_resource_rosa_create_test.go
- subsystem/cluster_waiter_test.go
- subsystem/default_ingress_resource_test.go
- subsystem/group_membership_resource_test.go
- subsystem/machine_pool_resource_test.go
This commit also fixes [OCM-5753](https://issues.redhat.com//browse/OCM-5753):
* In case of timeout and state not "READY" return error
**Which issue(s) this PR fixes**:
Fixes [OCM-5753](https://issues.redhat.com//browse/OCM-5753), [OCM-5399](https://issues.redhat.com//browse/OCM-5399)
**Checklist**
> OCM-5399 | fix: Remove duplicated wait function

- docs/data-sources/cluster_rosa_classic.md
- provider/clusterrosaclassic/cluster_rosa_classic_datasource.go
Fixes #[OCM-6092](https://issues.redhat.com/browse/OCM-6092)
**Checklist**
> OCM-6092 | fix: add "create_admin_user" in cluster datasource

- tests/OWNERS
I updated the OWNERS file according to our contributor change.
Updating #
[OCM-6335](https://issues.redhat.com//browse/OCM-6335) | ci: Update the OWNERS in rhcs automation
**Checklist**
> OCM-6335 | ci: Update the OWNERS in rhcs automation

- docs/resources/cluster_rosa_hcp.md
- provider/clusterrosa/classic/cluster_rosa_classic_resource.go
- provider/clusterrosa/hcp/datasource.go
- provider/clusterrosa/hcp/resource.go
- provider/clusterrosa/hcp/state.go
- provider/common/cluster_waiter.go
- provider/common/mock_clusterwait.go
- subsystem/hcp/cluster_resource_test.go
[OCM-6344](https://issues.redhat.com//browse/OCM-6344)
**Checklist**
> OCM-6344 | feat: add a waiter for std compute nodes

- docs/data-sources/hcp_machine_pool.md
- provider/machinepool/classic/machine_pool_datasource.go
- provider/machinepool/hcp/machine_pool_datasource.go
[OCM-5758](https://issues.redhat.com//browse/OCM-5758)
**Checklist**
> OCM-5758 | fix: missing attributes from datasource of hcp mp

- CHANGELOG.md
Update Changelog with versions v1.5.0 and v1.5.1
Fixes: [OCM-6074](https://issues.redhat.com//browse/OCM-6074)
**Checklist**
> OCM-6074: Update Changelog with versions v1.5.0 and v1.5.1

- provider/machinepool/hcp/machine_pool_resource.go
- subsystem/hcp/machine_pool_resource_test.go
[OCM-5758](https://issues.redhat.com//browse/OCM-5758)
**Checklist**
> OCM-5758 | fix: allow to patch subnet of hcp mp

- docs/data-sources/cluster_rosa_hcp.md
- docs/data-sources/hcp_machine_pool.md
- provider/clusterrosa/hcp/datasource.go
- provider/machinepool/hcp/autoscaling.go
- provider/machinepool/hcp/aws_node_pool.go
- provider/machinepool/hcp/machine_pool_datasource.go
- provider/machinepool/hcp/machine_pool_resource.go
[OCM-5758](https://issues.redhat.com//browse/OCM-5758)
**Checklist**
> OCM-5758 | fix: hcp-cluster and machine pool datasources

- tests/e2e/verfication_post_day1_test.go
- tests/utils/log/constants.go
**What this PR does / why we need it**: I hide some possible sensitive information from case log. So the log won't be deleted again
Fixes # [OCM-6703](https://issues.redhat.com//browse/OCM-6703)
**Checklist**
> OCM-6703 | ci: Hide possible sensitive message

- docs/resources/cluster_rosa_hcp.md
- provider/clusterrosa/hcp/resource.go
- subsystem/hcp/cluster_resource_test.go
[OCM-6769](https://issues.redhat.com//browse/OCM-6769)
**Checklist**
> OCM-6769 | fix: enforce some attributes for hcp

- docs/resources/cluster_rosa_classic.md
- docs/resources/cluster_rosa_hcp.md
- provider/clusterrosa/classic/cluster_rosa_classic_resource.go
- provider/clusterrosa/hcp/resource.go
[OCM-6810](https://issues.redhat.com//browse/OCM-6810)
**Checklist**
> OCM-6810 | fix: external id is computed only

- .gitignore
- tests/ci/profile_handler.go
- tests/ci/profiles/tf_classic_cluster_profiles.yml
- tests/e2e/cluster_upgrade_test.go
- tests/e2e/general_day_two_test.go
- tests/e2e/machine_pool_test.go
- tests/tf-manifests/aws/account-roles/rosa-classic/main.tf
- tests/tf-manifests/aws/account-roles/rosa-classic/output.tf
- tests/tf-manifests/aws/account-roles/rosa-classic/variables.tf
- tests/tf-manifests/aws/add-account-roles/rosa-classic/output.tf
- tests/tf-manifests/aws/add-account-roles/rosa-classic/variables.tf
- tests/tf-manifests/aws/oidc-provider-operator-roles/rosa-classic/main.tf
- tests/tf-manifests/aws/oidc-provider-operator-roles/rosa-classic/output.tf
- tests/tf-manifests/aws/shared-vpc-policy-and-hosted-zone/main.tf
- tests/tf-manifests/aws/shared-vpc-policy-and-hosted-zone/output.tf
- tests/tf-manifests/aws/shared-vpc-policy-and-hosted-zone/variables.tf
- tests/tf-manifests/aws/vpc/main.tf
- tests/tf-manifests/aws/vpc/variables.tf
- tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
- tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
- tests/utils/constants/constants.go
- tests/utils/constants/manifests.go
- tests/utils/exec/account-roles.go
- tests/utils/exec/cluster.go
- tests/utils/exec/dns-domain.go
- tests/utils/exec/oidc-provider-operator-roles.go
- tests/utils/exec/shared-vpc-policy-and-hosted-zone.go
- tests/utils/exec/vpc.go
E2e test is now able to run tests against Shared-VPC cluster.
CI jobs https://github.com/openshift/release/pull/49745
**Checklist**
**TODO**
> OCM-6701 | test: [TF provider] Add Shared-VPC test profile

- tests/ci/profiles/tf_classic_cluster_profiles.yml
Change channel group of STS classic cluster to stable.
> Change channel group of STS classic cluster to stable.

- docs/resources/rosa_oidc_config_input.md
- provider/oidcconfiginput/rosa_oidc_config_input_resource.go
This fix a leak that was detected by the pre-merge jobs (gitleaks7 leak tool)
**Which issue(s) this PR fixes** :
Fixes #[OCM-6889](https://issues.redhat.com//browse/OCM-6889)
**Checklist**
> OCM-6889 | fix: Fix rhcs_rosa_oidc_config_input.private_key attribute to be sensitive

- tests/ci/profiles/tf_hcp_cluster_profiles.yml
- tests/tf-manifests/rhcs/clusters/rosa-hcp/main.tf
> OCM-6387 | ci: Fix HCP cluster creation in CI

- tests/tf-manifests/aws/add-account-roles/rosa-classic/output.tf
This is a PR fix the CI failure in [job](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-critical-high-f3/1770776994649214976)
Fixes #[OCM-6960](https://issues.redhat.com//browse/OCM-6960)
**Checklist**
> OCM-6960 | ci: Fix failure of @OCP-63316

- docs/resources/cluster_rosa_hcp.md
- provider/clusterrosa/hcp/resource.go
[OCM-6992](https://issues.redhat.com//browse/OCM-6992)
**Checklist**
> OCM-6992 | fix: docs for wait for std compute nodes

- tests/tf-manifests/aws/oidc-provider-operator-roles/rosa-hcp/main.tf
This fix a small issue with HCP CI jobs
https://issues.redhat.com/browse/OCM-6387
**Checklist**
> OCM-6387 | ci: Fix HCP jobs

- docs/resources/hcp_machine_pool.md
- provider/machinepool/hcp/machine_pool_resource.go
[OCM-7006](https://issues.redhat.com//browse/OCM-7006)
**Checklist**
> OCM-7006 | fix: require aws node pool field

- provider/machinepool/hcp/machine_pool_resource.go
[OCM-7005](https://issues.redhat.com//browse/OCM-7005)
**Checklist**
> OCM-7005 | fix: improve error message for autoscaling and replicas

- tests/e2e/verfication_post_day1_test.go
Disable one test for HCP as it is not relevant
https://issues.redhat.com/browse/OCM-6387
**Checklist**
> OCM-6347 | ci: Fix HCP testing

- docs/resources/tuning_config.md
- provider/tuningconfigs/resource.go
[OCM-7019](https://issues.redhat.com//browse/OCM-7019)
**Checklist**
> OCM-7019 | fix: adjust docs to mention it requires jsonencode for tuning config

- provider/machinepool/hcp/machine_pool_resource.go
- subsystem/hcp/machine_pool_resource_test.go
[OCM-7022](https://issues.redhat.com//browse/OCM-7022)
**Checklist**
> OCM-7022 | fix: allow to supply version on create hcp mp

- docs/resources/hcp_default_ingress.md
- provider/defaultingress/hcp/resource.go
- subsystem/hcp/default_ingress_resource_test.go
[OCM-7042](https://issues.redhat.com//browse/OCM-7042)
**Checklist**
> OCM-7042 | fix: hcp ingress id should be read only

- docs/data-sources/hcp_machine_pool.md
- docs/resources/hcp_machine_pool.md
- provider/machinepool/hcp/aws_node_pool.go
- provider/machinepool/hcp/machine_pool_resource.go
- subsystem/hcp/machine_pool_resource_test.go
Allow the user to provide a list of security groups IDs for node pool creation.
Fixes #
**Checklist**
> OCM-6277 | Support day node pool for additional security groups

- provider/clusterrosa/classic/cluster_rosa_classic_resource.go
- provider/clusterrosa/hcp/resource.go
- provider/machinepool/hcp/machine_pool_resource.go
[OCM-7083](https://issues.redhat.com//browse/OCM-7083)
**Checklist**
> OCM-7083 | fix: use util to create version ID

- provider/tuningconfigs/resource.go
[OCM-7032](https://issues.redhat.com//browse/OCM-7032)
**Checklist**
> OCM-7032 | fix: append diags to ensure it catches the error

- examples/create_identity_provider/htpasswd/README.md
- examples/create_rosa_sts_cluster/classic_sts/cluster/output.tf
- provider/identityprovider/htpasswd.go
- provider/identityprovider/htpasswd/api.go
- provider/identityprovider/htpasswd/helpers.go
- provider/identityprovider/identity_provider_resource.go
- subsystem/identity_provider_resource_test.go
Adds functionality to HTPasswd IDPs allowing users to be added/updated/deleted
Fixes #[OCM-3006](https://issues.redhat.com//browse/OCM-3006)
https://issues.redhat.com/browse/OCM-3006
> OCM-3006 | feat: Add update functionality to HTPasswd IDPs

- provider/machinepool/hcp/aws_node_pool.go
- subsystem/hcp/machine_pool_resource_test.go
Check the maximal size of security groups provided by the user.
Fixes #
**Checklist**
> OCM-7177 | Create node pool with security groups - add validation

- tests/e2e/hcp_machine_pool_test.go
Update the automation script with bug fixing
Fixes # [OCM-7177](https://issues.redhat.com//browse/OCM-7177)
**Checklist**
> OCM-7177 | ci: Update automation script with bug fixing

- provider/machinepool/hcp/machine_pool_resource.go
- subsystem/hcp/machine_pool_resource_test.go
Check if the security groups' IDs were changed when updating the node pool, and error accordingly.
Fixes #
**Checklist**
> OCM-7176 | fix: Forbid updating the additional security groups

- go.mod
- go.sum
- tests/e2e/ingress_test.go
- tests/e2e/verfication_post_day1_test.go
- tests/tf-manifests/rhcs/ingresses/classic/main.tf
- tests/tf-manifests/rhcs/ingresses/classic/output.tf
- tests/tf-manifests/rhcs/ingresses/classic/variables.tf
- tests/tf-manifests/rhcs/resource-import/main.tf
- tests/utils/cms/cms.go
- tests/utils/constants/manifests.go
- tests/utils/exec/ingress.go
…0336
Automation testing for ingress updating
Fixes # [OCM-7293](https://issues.redhat.com//browse/OCM-7293)
**Checklist**
> OCM-7293 | ci: Automate tech debt for classic testing for OCP-70337|70336

- tests/ci/profile_handler.go
- tests/ci/profiles/tf_hcp_cluster_profiles.yml
- tests/e2e/hcp_machine_pool_test.go
- tests/e2e/verfication_post_day1_test.go
Set case ids in profiles + add some more coverage
https://issues.redhat.com/browse/OCM-7143
**Checklist**
> OCM-7143 Review CI profiles for day1 coverage

- docs/resources/default_ingress.md
- provider/defaultingress/classic/resource.go
- provider/defaultingress/classic/state.go
- provider/defaultingress/component_routes.go
- subsystem/default_ingress_resource_test.go
[OCM-6031](https://issues.redhat.com//browse/OCM-6031)
**Checklist**
> OCM-6031 | feat: allow to edit component routes of ingress

- tests/e2e/hcp_machine_pool_test.go
- tests/utils/cms/cms.go
Bypass the tags setting in case 73068 due to [OCM-7341](https://issues.redhat.com//browse/OCM-7341)
Fixes #[OCM-7378](https://issues.redhat.com//browse/OCM-7378)
**Checklist**
> OCM-7378 | ci: Bypass the tags setting in case 73068 due to OCM-7341

- docs/resources/hcp_machine_pool.md
- provider/machinepool/hcp/aws_node_pool.go
- provider/machinepool/hcp/machine_pool_resource.go
- subsystem/hcp/machine_pool_resource_test.go
[OCM-7341](https://issues.redhat.com//browse/OCM-7341)
**Checklist**
> OCM-7341 | fix: filter out cluster tags not supplied on mp hcp

- docs/data-sources/cluster_rosa_hcp.md
- docs/resources/cluster_rosa_hcp.md
- provider/clusterrosa/hcp/datasource.go
- provider/clusterrosa/hcp/resource.go
- provider/clusterrosa/hcp/resource_test.go
- provider/clusterrosa/hcp/state.go
- subsystem/hcp/cluster_resource_test.go
- subsystem/hcp/hcp_test.go
Signed-off-by: marcolan018 <llan@redhat.com>
support cluster admin day-1 creation for ROSA HCP cluster in terraform provider
Fixes # [OCM-6452](https://issues.redhat.com//browse/OCM-6452)
**Checklist**
> OCM-6452 | feat: support cluster admin day-1 creation for ROSA HCP cluster in terraform provider

- provider/machinepool/hcp/machine_pool_resource.go
- subsystem/hcp/machine_pool_resource_test.go
[OCM-7347](https://issues.redhat.com//browse/OCM-7347)
**Checklist**
> OCM-7347 | fix: allow to reset tuning configs

- tests/ci/profiles/tf_hcp_cluster_profiles.yml
- tests/e2e/classic_ingress_test.go
https://issues.redhat.com/browse/OCM-7565
Fixes #
**Checklist**
> OCM-7565 | fix: HCP CI

- tests/e2e/cluster_creation_test.go
- tests/e2e/idps_test.go
- tests/e2e/negative_day_one_test.go
- tests/e2e/verfication_post_day1_test.go
- tests/utils/cms/cms.go
- tests/utils/constants/http_code.go
new automated 73154 65928 66071
Logs see here https://privatebin.corp.redhat.com/?ede15f17cbdb1725#121xfBpCDaKGFLrA4ycXkiweGgFHtvM2fzwFCPqomM6
> OCM-7478 | ci: Automate OCP-73154,65928,66071

- tests/e2e/idps_test.go
[OCM-7590](https://issues.redhat.com//browse/OCM-7590) | ci: Update idp error message
> OCM-7590 | ci: Update idp error message

- tests/utils/exec/cluster-autoscaler.go
[OCM-7643](https://issues.redhat.com//browse/OCM-7643) | ci: Modify the member type of ResourceRange struct
> OCM-7643 | ci: Modify the member type of ResourceRange struct

- provider/clusterrosa/hcp/resource.go
- subsystem/hcp/cluster_resource_test.go
[OCM-6805](https://issues.redhat.com//browse/OCM-6805)
**Checklist**
> OCM-6805 | fix: allow patch of billing account id on hcp cluster

- tests/ci/profile_handler.go
- tests/e2e/cluster_autoscaler_day2_test.go
- tests/e2e/cluster_edit_test.go
- tests/e2e/cluster_misc_day2_test.go
- tests/e2e/hcp_ingress_test.go
- tests/e2e/hcp_machine_pool_test.go
- tests/e2e/negative_day_one_test.go
- tests/e2e/tuning_config.go
- tests/e2e/verfication_post_day1_test.go
- tests/tf-manifests/aws/proxy/main.tf
- tests/tf-manifests/aws/proxy/variables.tf
- tests/tf-manifests/aws/vpc/main.tf
- tests/tf-manifests/aws/vpc/variables.tf
- tests/tf-manifests/rhcs/clusters/rosa-hcp/main.tf
- tests/tf-manifests/rhcs/clusters/rosa-hcp/variables.tf
- tests/utils/constants/config.go
- tests/utils/constants/constants.go
- tests/utils/exec/cluster.go
- tests/utils/exec/proxy.go
- tests/utils/exec/vpc.go
- tests/utils/helper/assert.go
- tests/utils/helper/helper.go
[Logs](https://privatebin.corp.redhat.com/?63c02d1943acda3e#791L88pegSB9N1TBibkLgRhyZap1PoXPHaMVdYACCecH)
Automate Day1 negative cases
https://issues.redhat.com/browse/OCM-7142
**Checklist**
> OCM-7142 ci: Automate 72445/72449/72477/72486/72491/72496/72627/72468 (Day1 negative)

- .tekton/terraform-provider-rhcs-push.yaml
[OCM-7493](https://issues.redhat.com//browse/OCM-7493)
**Checklist**
> OCM-7493 | chore: update konflux settings

- tests/ci/profile_handler.go
- tests/e2e/cluster_autoscaler_day2_test.go
- tests/e2e/cluster_edit_test.go
- tests/e2e/hcp_ingress_test.go
- tests/e2e/hcp_machine_pool_test.go
- tests/e2e/idps_test.go
- tests/e2e/negative_day_one_test.go
- tests/e2e/tuning_config.go
- tests/e2e/verfication_post_day1_test.go
- tests/utils/exec/cluster.go
- tests/utils/exec/import.go
- tests/utils/exec/tf-exec.go
Fix some Medium&Low cases for HCP cluster
https://issues.redhat.com/browse/OCM-7839
**Checklist**
> OCM-7839 | ci: Fix M&L cases

- CHANGELOG.md
[OCM-7771](https://issues.redhat.com//browse/OCM-7771)
**Checklist**
> OCM-7771 | chore: changelog

- provider/oidcconfig/rosa_oidc_config_resource.go
- provider/oidcconfiginput/rosa_oidc_config_input_resource.go
[OCM-8085](https://issues.redhat.com//browse/OCM-8085)
**Checklist**
> OCM-8085 | fix: typo on message for oidc

- provider/clusterrosa/classic/cluster_rosa_classic_resource.go
- provider/clusterrosa/hcp/resource.go
[OCM-6806](https://issues.redhat.com//browse/OCM-6806)
**Checklist**
> OCM-6806 | fix: fail faster on cloud region change

- tests/e2e/classic_machine_pool_test.go
Fix construct vpc tag args with empty region error for test case 65071
Fixes #[OCM-8137](https://issues.redhat.com//browse/OCM-8137)
- [x ] CI
**Checklist**
- [x ] Subject and description added to both, commit and PR.
- [x ] Relevant issues have been referenced.
> OCM-8137 | ci: Fix construct vpc tag args with empty region error

- CONTRIBUTE.md
- docs/resources/hcp_cluster_autoscaler.md
- provider/autoscaler/hcp/resource.go
[OCM-8263](https://issues.redhat.com//browse/OCM-8263)
**Checklist**
> OCM-8263 | fix: adjust autoscaler docs to mention it is not currently available in hcp

- tests/e2e/cluster_autoscaler_day2_test.go
- tests/e2e/cluster_edit_test.go
> OCM-8279 | ci: Fix M/L HCP cases

- tests/ci/profiles/tf_hcp_cluster_profiles.yml
- tests/e2e/classic_ingress_test.go
- tests/e2e/classic_machine_pool_test.go
- tests/e2e/cluster_autoscaler_day2_test.go
- tests/e2e/cluster_edit_test.go
- tests/e2e/cluster_upgrade_test.go
- tests/e2e/hcp_ingress_test.go
- tests/e2e/hcp_machine_pool_test.go
- tests/e2e/idps_test.go
- tests/e2e/negative_day_one_test.go
- tests/utils/cms/cms.go
- tests/utils/openshift/openshift.go
Upgrade profiles for HCP
https://issues.redhat.com/browse/OCM-6348
https://issues.redhat.com/browse/OCM-6349
**Checklist**
> OCM-6348 | ci: Setup upgrade y and z profiles

- tests/e2e/cluster_upgrade_test.go
Fix CI upgrade nightlies
https://issues.redhat.com/browse/OCM-8316
**Checklist**
> OCM-8316 | ci: FIx HCP upgrade jobs

- tests/README.md
Document `RHCS_URL` variable
https://issues.redhat.com/browse/OCM-8334
**Checklist**
> OCM-8334 | ci: Document RHCS_URL

- provider/machinepool/classic/machine_pool_resource.go
[OCM-6718](https://issues.redhat.com//browse/OCM-6718)
**Checklist**
> OCM-6718 | fix: include fetchUserTagsOnly param for classic machine pools

- tests/tf-manifests/aws/account-roles/rosa-classic/main.tf
- tests/tf-manifests/aws/account-roles/rosa-hcp/main.tf
- tests/tf-manifests/aws/add-account-roles/rosa-classic/main.tf
- tests/tf-manifests/aws/add-account-roles/rosa-hcp/main.tf
- tests/tf-manifests/aws/oidc-provider-operator-roles/rosa-classic/main.tf
- tests/tf-manifests/aws/oidc-provider-operator-roles/rosa-hcp/main.tf
- tests/tf-manifests/rhcs/cluster-autoscaler/classic/main.tf
- tests/tf-manifests/rhcs/cluster-autoscaler/hcp/main.tf
- tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
- tests/tf-manifests/rhcs/clusters/rosa-hcp/main.tf
- tests/tf-manifests/rhcs/default-machine-pool/main.tf
- tests/tf-manifests/rhcs/dns/main.tf
- tests/tf-manifests/rhcs/idps/github/main.tf
- tests/tf-manifests/rhcs/idps/gitlab/main.tf
- tests/tf-manifests/rhcs/idps/google/main.tf
- tests/tf-manifests/rhcs/idps/htpasswd/main.tf
- tests/tf-manifests/rhcs/idps/ldap/main.tf
- tests/tf-manifests/rhcs/idps/multi-idp/main.tf
- tests/tf-manifests/rhcs/idps/openid/main.tf
- tests/tf-manifests/rhcs/ingresses/classic/main.tf
- tests/tf-manifests/rhcs/ingresses/hcp/main.tf
- tests/tf-manifests/rhcs/kubelet-config/main.tf
- tests/tf-manifests/rhcs/machine-pools/classic/main.tf
- tests/tf-manifests/rhcs/machine-pools/hcp/main.tf
- tests/tf-manifests/rhcs/resource-import/main.tf
- tests/tf-manifests/rhcs/rhcs-info/main.tf
- tests/tf-manifests/rhcs/tuning-config/main.tf
- tests/utils/constants/config.go
Fix provider definition in TF manifests, which should not have been deleted
https://issues.redhat.com/browse/OCM-8378
**Checklist**
> OCM-8378 | ci: Fix provider in TF manifests

- tests/e2e/idps_test.go
Update error message when idp url not set for test case 68939
Fixes #[OCM-8407](https://issues.redhat.com//browse/OCM-8407)
- [ x] CI
**Checklist**
- [ x] Subject and description added to both, commit and PR.
- [ x] Relevant issues have been referenced.
> OCM-8407 | ci: Update error message when idp url not set

- Makefile
- tests/e2e/cluster_edit_test.go
Add step to test case 72452
https://issues.redhat.com/browse/OCM-6806
**Checklist**
> OCM-6806 | ci: Fixing 72452

- tests/tf-manifests/aws/vpc/rosa-classic/main.tf
- tests/tf-manifests/aws/vpc/rosa-classic/variables.tf
- tests/utils/exec/vpc.go
We need to automate negative scenarios to make cluster goes into error.
Fixes #
[OCM-8441](https://issues.redhat.com//browse/OCM-8441) | test: Expose NAT gateway settings for vpc preparation.
**Checklist**
> OCM-8441 | test: Expose NAT gateway settings for vpc preparation.

- tests/e2e/negative_day_one_test.go
Fixes #[OCM-8416](https://issues.redhat.com//browse/OCM-8416)
- [ x] CI
**Checklist**
- [ x] Subject and description added to both, commit and PR.
- [ x] Relevant issues have been referenced.
> OCM-8416 | ci: Automate 64095

- tests/ci/profile_handler.go
Fixes #[OCM-8414](https://issues.redhat.com//browse/OCM-8414)
- [ x] CI
**Checklist**
- [ x] Subject and description added to both, commit and PR.
- [ x] Relevant issues have been referenced.
> OCM-8414 | ci: Fix 67576 of shared vpc profile creation

- tests/e2e/account_roles_test.go
- tests/utils/helper/iam_policy_fetcher.go
Fixes #[OCM-8415](https://issues.redhat.com//browse/OCM-8415)
- [ x] CI
**Checklist**
- [ x] Subject and description added to both, commit and PR.
- [ x] Relevant issues have been referenced.
> OCM-8415 | ci: Automate case 67574

- docs/guides/hosted-control-planes.md
- templates/guides/hosted-control-planes.md.tmpl
[OCM-7148](https://issues.redhat.com//browse/OCM-7148)
**Checklist**
> OCM-7148 | feat: include docs on usage of hcp cluster resource

- tests/tf-manifests/aws/account-roles/rosa-classic/main.tf
- tests/tf-manifests/aws/add-account-roles/rosa-classic/main.tf
- tests/tf-manifests/aws/oidc-provider-operator-roles/rosa-classic/main.tf
- tests/tf-manifests/aws/oidc-provider-operator-roles/rosa-classic/output.tf
- tests/utils/constants/constants.go
- tests/utils/helper/manifests_handler.go
Replaces the use of the old `rosa-sts/aws` module with the new `rosa-classic/rhcs` module in the test code 
Fixes #[OCM-5748](https://issues.redhat.com//browse/OCM-5748)
**Checklist**
> OCM-5748 | fix: Updated to use new RHCS module

- provider/machinepool/hcp/machine_pool_resource.go
- subsystem/hcp/machine_pool_resource_test.go
Signed-off-by: marcolan018 <llan@redhat.com>
Fixes # https://issues.redhat.com/browse/OCM-9113
**Checklist**
> OCM-9113 | fix: support delete kubelet configs from nodepool of hp cluster

- tests/e2e/negative_day_one_test.go
https://issues.redhat.com/browse/OCM-9092
**Checklist**
> OCM-9092 | ci: Fix id:64095

- tests/tf-manifests/aws/proxy/main.tf
It will fix the deprecated image from AWS for proxy start up
Fixes #
[OCM-9533](https://issues.redhat.com//browse/OCM-9533)
**Checklist**
> OCM-9533 | ci: update the deprecated image name for proxy preparation

- tests/ci/profile_handler.go
- tests/ci/profiles/tf_classic_cluster_profiles.yml
- tests/ci/profiles/tf_hcp_cluster_profiles.yml
- tests/e2e/cluster_creation_test.go
- tests/e2e/verification_post_day1_test.go
- tests/tf-manifests/aws/kms-second/main.tf
- tests/tf-manifests/aws/kms-second/output.tf
- tests/tf-manifests/aws/kms-second/variables.tf
- tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
- tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
- tests/tf-manifests/rhcs/clusters/rosa-hcp/main.tf
- tests/tf-manifests/rhcs/clusters/rosa-hcp/variables.tf
- tests/utils/constants/constants.go
- tests/utils/constants/manifests.go
- tests/utils/exec/cluster.go
- tests/utils/exec/tf-exec.go
- tests/utils/helper/parse_yaml.go
https://issues.redhat.com/browse/OCM-9274
**Checklist**
> OCM-9274 | ci: Automate ids:72466,72485,72516,72500,74748

- tests/ci/profile_handler.go
- tests/ci/profiles/tf_classic_cluster_profiles.yml
- tests/ci/profiles/tf_hcp_cluster_profiles.yml
- tests/e2e/verification_post_day1_test.go
- tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
- tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
- tests/tf-manifests/rhcs/clusters/rosa-hcp/main.tf
- tests/tf-manifests/rhcs/clusters/rosa-hcp/variables.tf
- tests/utils/cms/cms.go
- tests/utils/exec/cluster.go
Fixes #
[OCM-9035](https://issues.redhat.com//browse/OCM-9035)
**Checklist**
> OCM-9035 | ci: Automated 74096

- tests/ci/profiles/tf_classic_cluster_profiles.yml
- tests/ci/profiles/tf_hcp_cluster_profiles.yml
Move the testing to 4.16
Fixes #
[OCM-9561](https://issues.redhat.com//browse/OCM-9561)
**Checklist**
> OCM-9561 | ci: Move cluster versions to 4.16

- tests/e2e/classic_ingress_test.go
- tests/tf-manifests/rhcs/ingresses/classic/main.tf
- tests/tf-manifests/rhcs/ingresses/classic/variables.tf
- tests/utils/exec/ingress.go
**What this PR does / why we need it**: Automates test case OCP-73610 which is about testing the default_ingress component_routes option
Fixes #[OCM-8063](https://issues.redhat.com//browse/OCM-8063)
**Checklist**
> OCM-8063 | ci: Automated id:73610

- docs/data-sources/hcp_machine_pool.md
- docs/resources/hcp_machine_pool.md
- provider/machinepool/hcp/aws_node_pool.go
- provider/machinepool/hcp/machine_pool_resource.go
- subsystem/hcp/machine_pool_resource_test.go
Update hcp_rosa_machinepool resource to support IMDSv2 
Fixes #https://issues.redhat.com/browse/OCM-9162
**Checklist**
> OCM-9162 | feat: update machinepool resource to support IMDSv2

- tests/e2e/trusted_ips_test.go
- tests/tf-manifests/rhcs/trusted-ips/main.tf
- tests/tf-manifests/rhcs/trusted-ips/output.tf
- tests/utils/constants/manifests.go
- tests/utils/exec/trusted-ips.go
**What this PR does / why we need it**: Automates another test case: OCP-75233
Fixes #[OCM-9896](https://issues.redhat.com//browse/OCM-9896)
**Checklist**
> OCM-9896 | ci: Automated id:75233

- tests/e2e/classic_ingress_test.go
- tests/e2e/hcp_machine_pool_test.go
Fix ids 72514/75067
https://issues.redhat.com/browse/OCM-10084
**Checklist**
> OCM-10084 | ci: Fix ids:72514,75067 on HCP

- tests/ci/profiles/tf_hcp_cluster_profiles.yml
- tests/tf-manifests/rhcs/clusters/rosa-hcp/main.tf
- tests/tf-manifests/rhcs/clusters/rosa-hcp/variables.tf
- tests/tf-manifests/rhcs/machine-pools/hcp/main.tf
- tests/tf-manifests/rhcs/machine-pools/hcp/output.tf
- tests/tf-manifests/rhcs/machine-pools/hcp/variable.tf
- tests/utils/exec/machine-pools.go
Fixes #
**Checklist**
Output log for rosa-hcp-ad profile
$ rosa describe cluster -c rhcs-hcp-ad-q48 -o json | jq -r .aws.ec2_metadata_http_tokens
required
> OCM-8936 | ci: add support for imdsv2 for hcp cluster

- tests/ci/profiles/tf_classic_cluster_profiles.yml
- tests/ci/profiles/tf_hcp_cluster_profiles.yml
- tests/tf-manifests/rhcs/default-machine-pool/main.tf
- tests/tf-manifests/rhcs/default-machine-pool/output.tf
- tests/tf-manifests/rhcs/default-machine-pool/variable.tf
- tests/tf-manifests/rhcs/machine-pools/classic/main.tf
- tests/tf-manifests/rhcs/machine-pools/classic/output.tf
- tests/tf-manifests/rhcs/machine-pools/classic/variable.tf
https://issues.redhat.com/browse/OCM-10096
**Checklist**
> OCM-10096 | ci: Fix id:64757

- tests/tf-manifests/rhcs/default-machine-pool/main.tf
https://issues.redhat.com/browse/OCM-10096
**Checklist**
> OCM-10096 | ci: Fix default machine pool manifest

- tests/e2e/cluster_edit_test.go
- tests/utils/exec/cluster.go
```ginkgo -focus 63147 tests/e2e
time="2024-07-23T20:03:16+02:00" level=info msg="Running against RHCS URL: https://api.stage.openshift.com/"
Running Suite: e2e tests suite - /home/psuba/workspace/terraform-provider-rhcs/tests/e2e
========================================================================================
Random Seed: 1721757795
Will run 1 of 122 specs
time="2024-07-23T20:03:18+02:00" level=info msg="Loaded cluster profile configuration from profile rosa-sts-ad : map[additional_sg_number:4 admin_enabled:true autoscale:true byok:true byovpc:true ccs:true channel_group:stable cloud_provider:aws cluster_type:rosa-classic compute_machine_type:m5.2xlarge ec2_metadata_http_tokens:required etcd_encryption:true fips:false kms_key_arn:true labeling:true major_version:4.16 …
```
> OCM-9046 | test: updated case id:63147

- go.mod
- go.sum
- tests/ci/profile_handler.go
- tests/e2e/idps_test.go
- tests/e2e/negative_day_one_test.go
- tests/utils/helper/helper.go
Created new password generation for Admin and IDP HTPasswd passwords
Creation od IDP HTPasswd users occasionally failed with error: Attribute htpasswd.users[1].password password must contain lowercase\ncharacters, got: 1T/ETW4EZ65SX9G", }. 
The PR improve the way we generate password.
Fixes #8697
[OCM-8697](https://issues.redhat.com//browse/OCM-8697)
**Checklist**
> OCM-8697 | test: update case ids:65961, 73154, 66408, 66410

- provider/defaultingress/classic/resource.go
- provider/defaultingress/component_routes.go
- subsystem/default_ingress_resource_test.go
[OCM-10267](https://issues.redhat.com//browse/OCM-10267)
**Checklist**
> OCM-10267 | fix: accept to reset component routes by removing parent field

- tests/e2e/classic_ingress_test.go
- tests/tf-manifests/rhcs/ingresses/classic/main.tf
- tests/tf-manifests/rhcs/ingresses/classic/variables.tf
- tests/utils/exec/ingress.go
It should allow to remove component routes
https://issues.redhat.com/browse/OCM-10267
https://issues.redhat.com/browse/OCM-10247
**Checklist**
> OCM-10267 | ci: Update id:73610,75067

- tests/README.md
- tests/utils/log/constants.go
Fix the sensitive leak of CA and billing account
Fixes #
[OCM-10343](https://issues.redhat.com//browse/OCM-10343)
**Checklist**
> OCM-10343 | ci: Fix the sensitive leak of CA and billing account

- provider/defaultingress/classic/resource.go
- subsystem/default_ingress_resource_test.go
[OCM-10308](https://issues.redhat.com//browse/OCM-10308)
**Checklist**
> OCM-10308 | fix: validate individual component route against empty fields

- tests/OWNERS
update the OWNERS file of tests package
Fixes #
[OCM-10019](https://issues.redhat.com//browse/OCM-10019)
**Checklist**
> OCM-10019 | ci: update the OWNERS file

- CHANGELOG.md
[OCM-10346](https://issues.redhat.com//browse/OCM-10346)
**Checklist**
> OCM-10346 | chore: update changelogs to cover 1.6.3

- .tekton/terraform-provider-rhcs-push.yaml
[OCM-10346](https://issues.redhat.com//browse/OCM-10346)
https://github.com/konflux-ci/build-definitions/blob/main/task/buildah-10gb/0.2/MIGRATION.md
**Checklist**
> OCM-10346 | chore: fix konflux build

- tests/ci/profile_handler.go
- tests/tf-manifests/aws/shared-vpc-policy-and-hosted-zone/main.tf
- tests/tf-manifests/aws/shared-vpc-policy-and-hosted-zone/variables.tf
- tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
- tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
- tests/tf-manifests/rhcs/default-machine-pool/output.tf
- tests/tf-manifests/rhcs/default-machine-pool/variable.tf
- tests/tf-manifests/rhcs/ingresses/classic/variables.tf
- tests/tf-manifests/rhcs/machine-pools/classic/output.tf
- tests/tf-manifests/rhcs/machine-pools/classic/variable.tf
- tests/tf-manifests/rhcs/machine-pools/hcp/output.tf
- tests/tf-manifests/rhcs/machine-pools/hcp/variable.tf
- tests/utils/exec/cluster.go
- tests/utils/exec/shared-vpc-policy-and-hosted-zone.go
fix shared vpc creation failure on prow
Fixes #
[OCM-10469](https://issues.redhat.com//browse/OCM-10469)
**Checklist**
> OCM-10469 | ci: fix shared vpc creation failure on prow

- provider/clusterrosa/classic/cluster_rosa_classic_resource_test.go
- provider/clusterrosa/common/consts_test.go
- provider/clusterrosa/hcp/resource_test.go
[OCM-10500](https://issues.redhat.com//browse/OCM-10500)
**Checklist**
> OCM-10500 | chore: remove output from some unit tests

- build/ci-tf-e2e.Dockerfile
Replace latest terramform version in image due to it has a bug
Fixes #
[OCM-10542](https://issues.redhat.com//browse/OCM-10542)
**Checklist**
> OCM-10542 | ci: Replace latest terramform version in image due to it has a bug

- tests/e2e/account_roles_test.go
- tests/e2e/classic_ingress_test.go
- tests/e2e/classic_machine_pool_test.go
Fixing the CI failures to make CI running stable
Fixes #
[OCM-10643](https://issues.redhat.com//browse/OCM-10643)
**Checklist**
> OCM-10643 | ci: fix the ci failure of rosa-sts-ad medium+low cases

- tests/utils/exec/tf-exec.go
- tests/utils/log/logger.go
mask sensitive information in error, it will expose sensitive info when cluster creation failed
Fixes #
[OCM-10541](https://issues.redhat.com//browse/OCM-10541)
**Checklist**
> OCM-10541 | ci: mask sensitive information in error

- build/ci-tf-e2e.Dockerfile
- tests/ci/profile_handler.go
Reset rhcs CI using latest terraform version
Fixes #
[OCM-10778](https://issues.redhat.com//browse/OCM-10778)
**Checklist**
> OCM-10778 | ci: Reset rhcs CI using latest terraform version

- .tekton/terraform-provider-rhcs-push.yaml
[OCM-10760](https://issues.redhat.com//browse/OCM-10760)
**Checklist**
> OCM-10760 | chore: remove deprecated task

- provider/machinepool/classic/machine_pool_resource.go
- provider/machinepool/hcp/machine_pool_resource.go
- subsystem/classic/machine_pool_resource_test.go
- subsystem/hcp/machine_pool_resource_test.go
[OCM-10817](https://issues.redhat.com//browse/OCM-10817)
**Checklist**
> OCM-10817 | fix: check if tags are unknown prior to setting null

- tests/tf-manifests/aws/account-roles/rosa-classic/main.tf
- tests/tf-manifests/aws/add-account-roles/rosa-classic/main.tf
Fix test case id 65380. 
Fixes [OCM-9270](https://issues.redhat.com//browse/OCM-9270)
**Checklist**
> OCM-9270 | ci: include default account role prefix for classic cluster

- tests/e2e/hcp_machine_pool_test.go
- tests/tf-manifests/rhcs/machine-pools/hcp/output.tf
- tests/utils/exec/machine-pools.go
Test Nodepool can be created with empty tags
https://issues.redhat.com/browse/OCM-10817
**Checklist**
> OCM-10817 | ci: Update id:72510

- provider/oidcconfig/rosa_oidc_config_resource.go
- subsystem/classic/oidc_config_resource_test.go
Moves fetching thumbprint when creating oidc config resource to backend (CS) to avoid issues with proxies
Fixes #
[OCM-10200](https://issues.redhat.com//browse/OCM-10200)
**Checklist**
> OCM-10200 | feat: Implement thumbprint API changes

- tests/ci/profile_handler.go
- tests/tf-manifests/aws/shared-vpc-policy-and-hosted-zone/main.tf
- tests/tf-manifests/aws/shared-vpc-policy-and-hosted-zone/output.tf
- tests/utils/exec/shared-vpc-policy-and-hosted-zone.go
Use shared-vpc TF module in tests
https://issues.redhat.com/browse/OCM-10873
**Checklist**
> OCM-10873 | ci: Use shared vpc module in tests

- provider/autoscaler/classic/resource.go
- provider/autoscaler/hcp/resource.go
- provider/autoscaler/validators.go
- subsystem/classic/cluster_autoscaler_resource_test.go
[OCM-5019](https://issues.redhat.com//browse/OCM-5019)
**Checklist**
> OCM-5019 | fix: validates negative durations

- OWNERS
This PR aligns the QE approvers with those of the ROSA CLI project. This is to make it easier for the QE team to self-review and approve their own work without waiting for select maintainers to come online.
**Checklist**
> OCM-11003 | chore: Aligned QE Approvers with those of ROSA CLI project

- provider/machinepool/classic/machine_pool_resource.go
- provider/machinepool/hcp/machine_pool_resource.go
- subsystem/classic/machine_pool_resource_test.go
- subsystem/hcp/machine_pool_resource_test.go
[OCM-11030](https://issues.redhat.com//browse/OCM-11030)
**Checklist**
> OCM-11030 | fix: honor current setting instead of populating as nil

- examples/create_identity_provider/github/variables.tf
- examples/create_identity_provider/gitlab/variables.tf
- examples/create_identity_provider/google/variables.tf
- examples/create_identity_provider/openid/variables.tf
- tests/tf-manifests/rhcs/idps/github/variables.tf
- tests/tf-manifests/rhcs/idps/gitlab/variables.tf
- tests/tf-manifests/rhcs/idps/google/variables.tf
- tests/tf-manifests/rhcs/idps/multi-idp/variables.tf
- tests/tf-manifests/rhcs/idps/openid/variables.tf
[OCM-10738](https://issues.redhat.com//browse/OCM-10738)
**Checklist**
> OCM-10738 | feat: add sensitive to passwords/secret attributes

- tests/e2e/account_roles_test.go
https://issues.redhat.com/browse/OCM-10997
**Checklist**
> OCM-10997 | ci: Fix id 65380,72510

- docs/guides/upgrading-classic-cluster.md
- docs/guides/upgrading-hcp-cluster.md
- templates/guides/upgrading-classic-cluster.md.tmpl
- templates/guides/upgrading-hcp-cluster.md.tmpl
https://issues.redhat.com/browse/OCM-10612
**Checklist**
> OCM-10612 | feat: adjust docs for upgrading Classic/HCP clusters

- examples/create_identity_provider/htpasswd/variables.tf
- tests/ci/profile_handler.go
- tests/tf-manifests/aws/shared-vpc-policy-and-hosted-zone/main.tf
- tests/tf-manifests/aws/shared-vpc-policy-and-hosted-zone/output.tf
- tests/tf-manifests/aws/vpc/rosa-hcp/variables.tf
- tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
- tests/tf-manifests/rhcs/idps/htpasswd/variables.tf
- tests/tf-manifests/rhcs/idps/ldap/variables.tf
- tests/utils/exec/shared-vpc-policy-and-hosted-zone.go
Fix as https://github.com/terraform-redhat/terraform-provider-rhcs/commit/aa7f261c60215c09f21f6e13ce055b6130083804 was merged too fast
https://issues.redhat.com/browse/OCM-10873
**Checklist**
> OCM-10873 | ci: Fix Shared VPC

- provider/clusterrosa/common/consts.go
- provider/clusterrosa/common/consts_test.go
[OCM-11186](https://issues.redhat.com//browse/OCM-11186)
**Checklist**
> OCM-11186 | fix: adjust user role RE

- provider/autoscaler/classic/resource.go
- tests/e2e/cluster_autoscaler_day2_test.go
+ small fix on provider
https://issues.redhat.com/browse/OCM-5019
**Checklist**
> OCM-5019 | ci: Updated/Created ids 76199,72526

- CHANGELOG.md
[OCM-10344](https://issues.redhat.com//browse/OCM-10344)
**Checklist**
> OCM-10344 | chore: update changes for 1.6.4

- tests/e2e/account_roles_test.go
- tests/e2e/dns_test.go
- tests/e2e/hcp_ingress_test.go
- tests/e2e/verification_post_day1_test.go
Issues were introduced by https://github.com/terraform-redhat/terraform-provider-rhcs/commit/9a83aff96c46fba109a8e7aefe72b6c779a762bf
Issue: https://issues.redhat.com/browse/OCM-11280
**Checklist**
> OCM-11280 | ci: Fix tests panicking in BeforeEach

- provider/registry_config/helpers.go
In day1, we were not setting the value on this parameter due to a custom
diff detector that was not updated after changes in 688baba3c8173bdc7c05eea8660139303eff089e
We now consider also an empty list as change in line with the other parameters.
[OCM-11554](https://issues.redhat.com//browse/OCM-11554)
**Checklist**
> OCM-11554 | fix for allowedRegistriesForImport

- tests/e2e/account_roles_test.go
- tests/e2e/cluster_edit_test.go
- tests/e2e/kubelet_config_test.go
https://issues.redhat.com/browse/OCM-11748
**Checklist**
> OCM-11748 | ci: Fix ids 65380,76501,70128

- tests/ci/profiles/tf_hcp_cluster_profiles.yml
> OCM-9890 | ci: include worker_disk_size for profile rosa-hcp-ad

- CHANGELOG.md
[OCM-11660](https://issues.redhat.com//browse/OCM-11660)
**Checklist**
> OCM-11660 | chore: bump changelogs to 1.6.5

- provider/clusterrosa/common/consts.go
**What this PR does / why we need it**: updated to allow iam role arn for creator arn
**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story (OCM-xxxx)*: https://github.com/terraform-redhat/terraform-provider-rhcs/issues/823
Fixes #
**Checklist**
> fix: updated to allow iam role for creator arn

- provider/machinepool/classic/machine_pool_resource.go
- provider/machinepool/hcp/machine_pool_resource.go
- subsystem/classic/machine_pool_resource_test.go
- subsystem/hcp/machine_pool_resource_test.go
[OCM-12047](https://issues.redhat.com//browse/OCM-12047)
**Checklist**
> OCM-12047 | fix: allow standard pools to be imported when tags are empty instead of null

- CHANGELOG.md
[OCM-12146](https://issues.redhat.com//browse/OCM-12146)
**Checklist**
> OCM-12146 | chore: bump changelogs to v1.6.6

- .tekton/terraform-provider-rhcs-push.yaml
> OCM-12146 | chore: include 'rpms-signature-scan' to konflux build

- tests/e2e/classic_machine_pool_test.go
- tests/e2e/hcp_machine_pool_test.go
https://issues.redhat.com/browse/OCM-12064
**Checklist**
> OCM-12064 | ci: Fix ids 63139,72514

- tests/ci/profiles/tf_hcp_cluster_profiles.yml
- tests/e2e/verification_post_day1_test.go
[OCM-12058](https://issues.redhat.com//browse/OCM-12058) | ci: Automate id:77065
logs: https://privatebin.corp.redhat.com/?8bd689d752689e7f#DzwiLG7XicDz7cMzHEEwM52pynkHLh74ErV9gZw25rs2
> OCM-12058 | ci: Automate id:77065

- provider/clusterrosa/hcp/resource.go
> OCM-12071 | fix: remove rosa_creatorn_arn update validation

- docs/resources/cluster_rosa_hcp.md
- provider/clusterrosa/common/consts.go
- provider/clusterrosa/hcp/resource.go
> OCM-12402 | fix: increase hcp cluster readiness timeout

- provider/clusterrosa/common/properties.go
> OCM-12526 | fix: still return the plan map when error

- tests/e2e/cluster_edit_test.go
[OCM-12390](https://issues.redhat.com//browse/OCM-12390) | ci: Automate id:72455 for [OCM-12390](https://issues.redhat.com//browse/OCM-12390):
New change happens with [OCM-12390](https://issues.redhat.com//browse/OCM-12390), update existed test case for this change.
log: https://privatebin.corp.redhat.com/?c911a93eeae5d37a#57bQxT6Ue2S9qjDEUX9KKX9hBTo5qr54jtSG3tYTuVdX
> OCM-12390 | ci: Automate id:72455 for OCM-12390

- provider/identityprovider/github.go
- subsystem/classic/identity_provider_resource_test.go
- tests/e2e/idps_test.go
Related to https://github.com/terraform-redhat/terraform-provider-rhcs/pull/851
[OCM-12442](https://issues.redhat.com/browse/OCM-12442)
Fixes #
**Checklist**
> OCM-12442 | feat: Added github hostname validation

- CHANGELOG.md
> OCM-12392 | chore: bump changelogs to v1.6.7

- docs/data-sources/policies.md
- provider/autoscaler/classic/resource.go
- provider/autoscaler/hcp/resource.go
- provider/clusterrosa/classic/cluster_rosa_classic_datasource.go
- provider/clusterrosa/classic/cluster_rosa_classic_resource.go
- provider/clusterrosa/hcp/datasource.go
- provider/clusterrosa/hcp/resource.go
- provider/clusterwaiter/cluster_waiter_resource.go
- provider/common/cluster_waiter.go
- provider/defaultingress/classic/resource.go
- provider/defaultingress/hcp/resource.go
- provider/groupmembership/group_membership_resource.go
- provider/info/consts.go
- provider/info/info_data_source.go
- provider/kubeletconfig/kubeletconfig_resource.go
- provider/machinepool/classic/machine_pool_resource.go
- provider/machinepool/hcp/machine_pool_resource.go
- provider/ocm_policies/classic/ocm_policies_data_source.go
- provider/ocm_policies/classic/ocm_policies_state.go
- provider/tuningconfigs/resource.go
- subsystem/classic/rosa_ocm_policies_data_source_test.go
This PR introduces support for ROSA GovCloud environments. 
It adds explicit token refreshes during the cluster wait process, which is required for support in ROSA GovCloud installations, since FedRAMP requirements prohibit a refresh token from having a lifespan greater than 15 minutes (compared to 10 hours on the commercial side). Without this feature, the token times out while waiting for a ROSA cluster to come up.
It also adds GovCloud OCM AWS Account IDs and a GovCloud-only operator policy (openshift_aws_vpce_operator_avo_aws_creds_policy)
**Checklist**
> OCM-13503 | feat: ROSA GovCloud Support

- OWNERS
- tests/OWNERS
**What this PR does / why we need it**: Adds me as an approver so I can merge test automation updates
Fixes #[OCM-14463](https://issues.redhat.com//browse/OCM-14463)
**Checklist**
> OCM-14463 | chore: Add myself as an approver

- tests/e2e/negative_day_one_test.go
**What this PR does / why we need it**: Automates OCP-63835
Fixes # [OCM-4500](https://issues.redhat.com//browse/OCM-4500)
**Checklist**
> OCM-4500 | test: automated id:63835

- tests/e2e/cluster_autoscaler_day2_test.go
- tests/e2e/hcp_machine_pool_test.go
- tests/tf-manifests/aws/proxy/main.tf
**What this PR does / why we need it**: Fixes id:72514,72526
Fixes #[OCM-14870](https://issues.redhat.com//browse/OCM-14870)
**Checklist**
> OCM-14780 | test: Fixing id:72514,72526, and filter owner for proxy AMI

- tests/tf-manifests/aws/proxy/main.tf
**What this PR does / why we need it**: Updates proxy AMI to use a filter that won't need to be updated so frequently
Fixes #[OCM-15376](https://issues.redhat.com//browse/OCM-15376)
**Checklist**
> OCM-15376 | ci: Update proxy AMI image to select most recent image

- .tekton/terraform-provider-rhcs-push.yaml
Fixes [OCM-15301](https://issues.redhat.com//browse/OCM-15301) (release blocker)
> OCM-15301 | ci: Fix sast-unicode-check job

- .tekton/terraform-provider-rhcs-push.yaml
Adds SHA values to unbreak build pipeline
> OCM-15301 | ci: Change sha on 2 tasks

- .tekton/terraform-provider-rhcs-push.yaml
Changes digest for unicode Konflux task
> OCM-15301 | ci: Update digest for unicode task

- .tekton/terraform-provider-rhcs-push.yaml
Fixes snyk-check-oci-ta task by changing digest to correct format
> OCM-15301 | ci: Fix snyk digest for konflux task

- .tekton/terraform-provider-rhcs-push.yaml
Removes task which is not needed, and needs information we do not have currently in the Konflux config
> OCM-15301 | ci: Remove unneeded task

- .tekton/terraform-provider-rhcs-push.yaml
Remove workspaces for sast unicode check task
> OCM-15301 | ci: Remove workspaces for unicode check

- .tekton/terraform-provider-rhcs-push.yaml
Add workspace block to failing task
> OCM-15301 | ci: Add workspace to sast-unicode-check task

- .tekton/terraform-provider-rhcs-push.yaml
To attempt retriggering the pipeline, which failed to trigger with the previous MR
> OCM-15301 | ci: Remove init task + change quay digest for other one

- .tekton/terraform-provider-rhcs-push.yaml
> OCM-15301 | ci: Delete duplicate jobs + change digest on old ones

- .tekton/terraform-provider-rhcs-push.yaml
> OCM-15301 | ci: Remove final duplicated job and change digest

- .tekton/terraform-provider-rhcs-push.yaml
The goal is to get the Konflux build pipeline passing the [Conforma/EC check|https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-terraform-tenant/applications/terraform-provider-rhcs/integrationtests/terraform-provider-rhcs-enterprise-contract/pipelineruns].
Fixes [KFLUXSPRT-2853](https://issues.redhat.com//browse/KFLUXSPRT-2853)
**Checklist**
> Konflux pipeline fixes

- .tekton/terraform-provider-rhcs-push.yaml
> OCM-15301 | chore: move konflux into oci-ta tasks

- .tekton/terraform-provider-rhcs-push.yaml
> OCM-15301 | chore: adjust konflux build

- provider/clusterrosa/hcp/resource.go
- provider/proxy/utils.go
- provider/proxy/utils_test.go
- subsystem/hcp/cluster_resource_test.go
> OCM-13095 | fix: remove no proxy zero egress default domains

- tests/tf-manifests/aws/proxy/main.tf
**What this PR does / why we need it**: Updates the proxy AMI image (really just tells it to ignore any monthly version changes), and makes the scp command to the proxy work a bit better when ran on a system with a lot of ssh configuration
Fixes #[OCM-16456](https://issues.redhat.com//browse/OCM-16456)
**Checklist**
> OCM-16456 | ci: Update proxy AMI image, change scp command to be more reliable locally

- docs/index.md
- tests/e2e/negative_day_one_test.go
- tests/e2e/tuning_config_test.go
- tests/utils/profilehandler/handler.go
**What this PR does / why we need it**: Fixes a few test cases
Fixes #[OCM-17240](https://issues.redhat.com//browse/OCM-17240)
**Checklist**
Local output: https://privatebin.corp.redhat.com/?dc13c5e9949ac7a4#DNppDKjGniAo3rhxSbXh8za34u3gjwokbeNADFCAchU9
> OCM-17240 | test: Fixing id:64095 and id:72521

- .tekton/terraform-provider-rhcs-push.yaml
Updates 2 task refs which did not use trusted tasks
Fixes #[OCM-18505](https://issues.redhat.com//browse/OCM-18505)
**Checklist**
> OCM-18505 | ci: Update taskrefs
