.github/workflows/publish-release.yaml

As it was mentioned [here](https://developer.hashicorp.com/terraform/tutorials/providers/provider-release-publish#add-github-action-workflow), the [release yaml ](https://github.com/hashicorp/terraform-provider-scaffolding/blob/main/.github/workflows/release.yml#L17)should include the write permissions

Add a write permissiong to the release workflow

---

provider/cluster_rosa_classic_resource.go
provider/cluster_rosa_classic_state.go
provider/cluster_state.go
provider/machine_pool_resource.go
provider/machine_pool_state.go
subsystem/cluster_resource_rosa_test.go
subsystem/machine_pool_resource_test.go
subsystem/main_test.go
subsystem/rosa_operator_roles_data_source_test.go

The changes in this PR are: 
* Support trustBundle string in creating a cluster in rosa sts resource 
* Support adding labels and taints in machine pool resource
* Fix a flakiness index order in ROSA Operator IAM roles data source
* Support adding computeLabels for the default machine pool in rosa sts cluster resource

Matching rosa

---

docs/resources/cluster_rosa_classic.md
docs/resources/machine_pool.md
provider/cluster_rosa_classic_resource.go
provider/cluster_rosa_classic_state.go
subsystem/cluster_resource_rosa_test.go
subsystem/main_test.go

In this PR I added the ability to track cluster state in ocm_cluster_rosa_classic resource - in create and destroy, by polling the cluster state. 
The user can set a new attribute called `wait_with_timeout` (in minutes) and the Create and Destroy method waits for cluster state in that same timeout.

Address cluster state

---

provider/cluster_rosa_classic_resource.go
provider/cluster_rosa_classic_resource_test.go
provider/cluster_rosa_classic_state.go

The `dns.base_domain` attribute is immediately available from the API when creating a new cluster, and can be useful in further configuration of resources within the same terraform run.
This value can be queried using `rosa describe cluster -c id`. The value from the ROSA CLI is always `[name].[dns.base_domain]`, which is why the domain attribute prepends the cluster name in this proposed feature.
An example use would be configuring an OpenID IdP using the domain attribute for the callback URL.
This creates a nice workflow where the cluster creation can begin in the background (required already because of the OIDC Provider dependency), and the `ocm_identity_provider` of type OpenID can be created in the same terraform run, which will trigger the wait for cluster install completion loop on …

Add domain attribute to cluster_rosa_classic resource

---

docs/resources/identity_provider.md
provider/cluster_resource.go
provider/cluster_rosa_classic_resource.go
provider/common/attribute_validator.go
provider/common/helpers.go
provider/identity_provider_resource.go
provider/identity_provider_state.go
provider/idps/github.go
provider/machine_pool_resource.go
subsystem/identity_provider_resource_test.go

- Created new `idps` package. In future PRs will move all the providers
to this package.
- Added ability to create a github idp.
- Added an attribute validator helper struct for easy validation
construction.
- Added subsytem tests
Validations are based on ROSA CLI

OCM-174: Added GitHub IDP provider attrs

---

docs/resources/identity_provider.md
provider/identity_provider_resource.go
provider/identity_provider_state.go
provider/idps/github.go
provider/idps/gitlab.go
provider/idps/htpasswd.go
provider/idps/ldap.go
provider/idps/openid.go

All IDPs are now located in /provider/idps/
this includes:
- schemas
- structs (states)
- validations (if exists)
- updated golang string slices to terraform types.List
- Added missing descriptions + updated docs
- provider builders

OCM-177: Move all identity providers to internal pkg

---

go.mod
go.sum
provider/cluster_rosa_classic_resource.go
provider/cluster_rosa_classic_resource_test.go
provider/cluster_rosa_classic_state.go
subsystem/cluster_resource_rosa_test.go

OCM-136: Allow specifying channel group name

---

Makefile
ci/e2e/terraform_provider_ocm_fullcycle_test.go

Some variables were missing or given with the wrong names.
In addition, remove junit.xml reporting as we don't really use it right now (and it's causing some permission problems in prow)

Fix e2e flow missing variables

---

docs/resources/cluster_rosa_classic.md
docs/resources/machine_pool.md
go.mod
go.sum
provider/cluster_rosa_classic_resource.go
provider/cluster_rosa_classic_resource_test.go
provider/cluster_rosa_classic_state.go
provider/common/helpers.go
provider/enum_value_validator.go
subsystem/cluster_resource_rosa_test.go

Adding support for http_tokens_state field. This field can be used only
from 4.11.0 and have 2 options: optional/required

OCM-141: Terraform for IMDSv2 support

---

provider/cluster_rosa_classic_resource.go

It fixed e2e test error
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to ocm_cluster_rosa_classic.rosa_sts_cluster,
│ provider "provider[\"terraform.local/local/ocm\"]" produced an unexpected
│ new value: .aws_http_tokens_state: was null, but now cty.StringVal("").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵

Fixing issue with empty aws_http_tokens in ocm response

---

examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/variables.tf

this makes it easier to use the example as a blueprint and reference `main.tf` as a module.

refactor cluster_name, region and az into vars

---

ci/e2e/account_roles_files/main.tf
ci/e2e/terraform_provider_ocm_files/main.tf
ci/e2e/terraform_provider_ocm_files/variables.tf

1. In case openshift_Version is passed to cluster creation (as 4.12.15, 4.13.rc-7, etc) , the version for account_roles creation (rosa_openshift_version) can be extracted from this parameter
2. added channel variable (stable is the default)

fix account_roles to extract version from extended openshift_version

---

ci/e2e/terraform_provider_ocm_fullcycle_test.go

It causes the following error:
```
var.token
Enter a value: ╷
│ Error: No value for required variable
│
│   on variables.tf line 15:
│   15: variable token {
│
│ The root module input variable "token" is not set, and has no default
│ value. Use a -var or -var-file command line argument to provide a
value for
│ this variable.
╵
------------------------------
• [FAILED] [3522.636 seconds]
Terraform provider OCM test [AfterAll]
/alabama/terraform-provider-ocm/ci/e2e/terraform_provider_ocm_fullcycle_test.go:270
Cluster creation
/alabama/terraform-provider-ocm/ci/e2e/terraform_provider_ocm_fullcycle_test.go:263
creates a cluster using terraform-provider-ocm
/alabama/terraform-provider-ocm/ci/e2e/terraform_provider_ocm_fullcycle_test.go:264
```
(see …

Fix missing token variable when destroying roles

---

provider/cluster_rosa_classic_resource.go
provider/cluster_rosa_classic_resource_test.go
provider/cluster_rosa_classic_state.go
subsystem/cluster_resource_rosa_test.go

- Added new computed attribute, `ocm_properties` containing provider version/commit
- when creating a cluster we merge `properties` and `ocm_properties` into one map that is sent to OCM. This is so we keep `properties` backwards compatible.

OCM-335: Added provider version and commit to cluster properties

---

.gitignore
Makefile
README.md
ci/apply_folder.sh
ci/destroy_folder.sh
ci/post_apply_prow_setup.sh
ci/setup_prow_env.sh

- apply_folder (./ci/apply_folder.sh)
- destroy_folder (./ci/destroy_folder.sh)
Targets can be run locally or from PROW CI.
Running locally will target the (gitignored) folder `./playground`. You
can use this to debug and play with local builds of the provider. To
change the default playground location, set `$WORK_DIR` before running
make.
If running in OpenShift CI, `$WORK_DIR` is set to
`${SHARED_DIR}/work`. And will handle archiving/extracting the
state to/from the `SHARED_DIR`. Also passing kubeconfig/cluster_id to the SHARED_DIR.
No Parameters are needed.

OCM-274: Added 2 make targets

---

provider/rosa_operator_roles_data_source.go

In case failing to list the STS Operator Roles List "terraform apply" should fail and not continue to next step This is done in order to make it more clear for user what is the error In addition, added hint to user for checking the credentials (token)

OCM-759: add error to "rosa_operator_roles_data_source" in case get stsOperatorRolesList failure

---

examples/create_rosa_cluster/create_rosa_iam_cluster/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/variables.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/output.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/variables.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/output.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/output.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/variables.tf

In order to let the user control on the resources names and region, change those parameters to variables for managed and unmanaged clusters
Please notice: First commit is "make fmt_tf" auto results

Allow users to set cluster_name, cloud_region and hosted_zones

---

examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/output.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/output.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/README.md
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/output.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/variables.tf

Move OIDC provider creation to different directory, in order to give the user template how to run it, out of the cluster context This also include the OIDC config (relevant only for unmanaged scenario) and the operator IAM roles The managed and unmanaged cluster use this as module, but now user can easily remove this part from the cluster creation

Examples: Move OIDC provider creation to different module

---

examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/README.md
examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/variables.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/README.md
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/README.md
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/variables.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf

Also added option to seth the path in the managed and unmanaged clusters in order to allow using it from the clusters

OCM-2237: Add support for adding path to account roles in creation

---

examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/README.md
examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/variables.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/README.md
examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/cluster/variables.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/README.md
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/README.md
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/variables.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/README.md
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/variables.tf

Describing in the example files how to tag AWS resources using the variable 'tag'

OCM-2289: Add the option for tagging AWS resources in the example files

---

provider/cluster_rosa_classic_resource.go

When looking for available upgrades, if the cluster is on a non-default channel, append the channel name to the version id.

Pass non-default channel when looking for upgrades

---

build/ci-tf-bin.Dockerfile

Build images for both architectures and use them for testing binary.

OCM-2254: Add Dockerfiles for ARM and AMD64 binaries

---

README.md
examples/create_identity_provider/README.md
examples/create_identity_provider/github/README.md
examples/create_identity_provider/gitlab/README.md
examples/create_identity_provider/google/README.md
examples/create_identity_provider/htpasswd/README.md
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/README.md
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/README.md

This PR collects all of the post-cluster creation tasks. Using [this Bug Hunt document](https://docs.google.com/document/d/1x9U35yyypt-vmXBibKgp80RixlOuIim_sTFi-3HaKxU/edit), I plan to cover the following actions:
**Pre cluster installation:**
* Create account roles
**Cluster installation (day 1):**
* Create Rosa classic cluster with managed OIDC
* Create Rosa classic cluster with unmanaged OIDC
**Post cluster installation (day 2):**
* Modify Default Machine Pool 
* Change replica count
* Change Auto Scaling - enable/disable
* Change Labels
* Create Identity provider
The following identity providers are supported:
* Github
* Gitlab
* HTPasswd
* Google
* LDAP
* OpenID
* Update/Upgrade cluster

Day 2 Terraform Tasks

---

docs/upgrading-cluster.md
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf

This was introduced in https://github.com/terraform-redhat/terraform-provider-ocm/pull/136 This variable shouldn't be used

Remove acks_for variable added by mistake to example

---

ci/e2e/account_roles_files/main.tf
ci/e2e/oidc_configuration/cluster_with_managed_oidc_config/main.tf
ci/e2e/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
ci/e2e/terraform_provider_ocm_files/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/classic_sts/account_roles/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf

When indicating the required sts module version, use "=" instead of ">="

Fix examples to use specific version of the module

---

docs/modify-cluster.md
docs/resources/machine_pool.md
examples/create_machine_pool/README.md
examples/create_machine_pool/main.tf
examples/create_machine_pool/variables.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_unmanaged_oidc_config/variables.tf
provider/machine_pool_resource.go

Updated the Terraform documentation to show how to create machine pools, change the replica count, and enable autoscaling.

Updated documentation for modifying machine pools

---

provider/cluster_rosa_classic_resource.go

In the validator, we make sure that the user is not passing a "reserved/default" property key. This was done by checking the key against the 2 options: `rosa_tf_version` and `rosa_tf_commit`.
This refactor will be more future-proof. We can add more reserved properties and not touch the validator in that area.
We now try to get the value of the proposed key from the OCMProperties map. If found, we throw the error.

Refactoring the cluster properties validator

---

Makefile
README.md

Leave e2e image to e2e tests and use new ocm-tf-bin image for testing binary.

Update README.md for using new binary image.

---

.gitignore
provider/machine_pool_resource.go
provider/machine_pool_state.go
subsystem/machine_pool_resource_test.go

Support creating single AZ machine pool in a multi-az cluster. AZ can be designated by either specifying the AZ name or by providing a subnet id for byo VPC.

OCM-2493: Add support for 1AZ pool in mAZ cluster

---

examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf

Fix a space indentation issue on example OIDC managed cluster [variable.tf](https://github.com/terraform-redhat/terraform-provider-rhcs/blob/main/examples/create_rosa_cluster/create_rosa_sts_cluster/oidc_configuration/cluster_with_managed_oidc_config/variables.tf#L61)

Fix a minor space indentation issue

---

docs/index.md
provider/cluster_rosa_classic_resource.go
subsystem/cluster_resource_rosa_test.go

This change is done in order to avoid the requirement to have valid AWS credentials in the local machine, in which the terraform executed. This change include:
* Remove the relevant code from the provider
* changing the subsystem accordingly to the change
* Removing limitation from docs

OCM-2666: Remove AWS validations from rosa_cluster resource

---

ci/e2e/account_roles_files/main.tf
ci/e2e/oidc_configuration/cluster_with_managed_oidc_config/main.tf
ci/e2e/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
examples/create_account_roles/README.md
examples/create_account_roles/main.tf
examples/create_account_roles/output.tf
examples/create_account_roles/variables.tf
examples/create_rosa_sts_cluster/classic_sts/cluster/main.tf
examples/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf

This PR depends on that [PR](https://github.com/terraform-redhat/terraform-aws-rosa-sts/pull/22)
This PR allows supplying of an empty string for account_role_prefix. 
If the user supplies an empty string for the `account_role_prefix` variable, the module terraform-aws-rosa-sts will generate account_role_prefix and will use it in order to create the roles.

OCM-2361: Support generated account_role_prefix

---

provider/cluster_rosa_classic_resource.go
subsystem/cluster_resource_rosa_test.go
subsystem/main_test.go

Adds support for running `terraform import` to pull in a cluster.
**Usage:**
Add a minimal definition of the cluster to the `.tf` file:
```
resource "rhcs_cluster_rosa_classic" "mycluster" { }
```
Run import on that resource, passing the cluster's id:
```console
$ terraform import rhcs_cluster_rosa_classic.mycluster 24q7p8vthmm5erql10nn3qovq45juhsk
rhcs_cluster_rosa_classic.mycluster: Importing from ID "24q7p8vthmm5erql10nn3qovq45juhsk"...
data.rhcs_policies.all_policies: Reading...
rhcs_cluster_rosa_classic.mycluster: Import prepared!
Prepared rhcs_cluster_rosa_classic for import
rhcs_cluster_rosa_classic.mycluster: Refreshing state... [id=24q7p8vthmm5erql10nn3qovq45juhsk]
data.rhcs_policies.all_policies: Read complete after 1s
data.aws_caller_identity.current: Reading... …
```

OCM-2360: Add support for importing a classic cluster

---

provider/cluster_rosa_classic_resource.go
provider/cluster_waiter_resource.go
subsystem/cluster_resource_rosa_test.go
subsystem/cluster_waiter_test.go

This PR adds the ability to reconcile a cluster that was created by TF, but then was removed via a different method, Not via terraform.
In this case, And if the user still has the cluster resource in his `.tf` files. Upon an `apply`, the provider will re-create the cluster.
Before this PR, the provider would have error out, since it could not find the cluster defined in the state.
Note: This PR also modifies the `cluster_waiter`. This is because we now do need to update the resource if the cluster id has changed. Also moved the timeout validation into a `validator` **this will now throw an error** if the user has set the `timeout` to a negative number. Unlike it worked before, printing a warning and using the default value.
The polling (`cluster_waiter`) was also moved to a new function, …

OCM-2645: Recreate cluster if it was deleted from other client

---

.goreleaser.yaml

This is done in order to add the build properties (version and commit)

OCM-2702: Add ldflag section to build in goreleaser.yaml

---

ci/e2e/account_roles_files/main.tf
ci/e2e/oidc_configuration/cluster_with_managed_oidc_config/main.tf
ci/e2e/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
examples/create_account_roles/main.tf
examples/create_rosa_sts_cluster/classic_sts/cluster/main.tf
examples/create_rosa_sts_cluster/oidc_configuration/oidc_provider/main.tf
examples/list_versions/main.tf
examples/list_versions/output.tf
examples/list_versions/variables.tf
tests/tf-manifests/aws/account-roles/main.tf
tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf

This PR is updating the examples file:
1. To include the `all_versions` variable while creating account roles using the module
2.  To include the most updated version of the module
This PR is depends on : https://github.com/terraform-redhat/terraform-aws-rosa-sts/pull/24

OCM-2415: Fixing the example of list_versions usage

---

.gitignore
ci/e2e/account_roles_files/main.tf
ci/e2e/account_roles_files/variables.tf
ci/e2e/oidc_configuration/cluster_with_managed_oidc_config/main.tf
ci/e2e/oidc_configuration/cluster_with_managed_oidc_config/variables.tf
ci/e2e/oidc_configuration/cluster_with_unmanaged_oidc_config/main.tf
ci/e2e/oidc_configuration/cluster_with_unmanaged_oidc_config/variables.tf
ci/e2e/terraform_provider_ocm_files/main.tf
ci/e2e/terraform_provider_ocm_files/variables.tf
ci/setup_prow_env.sh

PR for using  explicit aws_key/secret in main.tf of ci/e2e/*
#relates to https://issues.redhat.com/browse/OCM-2459

OCM-2769: change to explicit aws credentials

---

provider/machine_pool_resource.go
provider/value_cannot_be_changed_modifier.go
subsystem/machine_pool_resource_test.go

Tested importing:
- 1AZ cluster, 1AZ pool
- mAZ cluster, 1AZ pool
- mAZ cluster, mAZ pool
Note: I removed the verification that replicas is a multiple of 3 in the case of mAZ pools. OCM provides this validation separately. The reason for the removal from the TF code is that it was causing a problem during updates after state import wrt the 1AZ optional fields for mAZ clusters. It would have required additional API queries to read the cluster object.

OCM-2636: Enable importing machine pools

---

docs/resources/identity_provider.md
examples/create_identity_provider/htpasswd/README.md
examples/create_identity_provider/htpasswd/main.tf
examples/create_identity_provider/htpasswd/variables.tf
provider/identity_provider_resource.go
provider/idps/htpasswd.go
subsystem/identity_provider_resource_test.go

This commit changes the way the user is passing user credentials into htpasswd IDP resource.
Before this commit, a single username and password was passed. 
This commit/PR moves to `users`, a list of user credentials.
Updated docs and examples as well.

OCM-2637: [BREAKING] htpasswd IDP user list

---

CHANGELOG.md
go.mod
provider/cluster_rosa_classic_resource.go
subsystem/cluster_resource_rosa_test.go

While updating the Proxy needs to initialize the state.Proxy object if this is the first time to be set.

OCM-3102: Fixing a bug in while updating the Proxy attribute

---

CHANGELOG.md
provider/cluster_rosa_classic_resource.go
subsystem/cluster_resource_rosa_test.go

Since OCM returns `REDUCTED` as values of sensitive content, the provider was populating `REDUCTED` as the new state for `additional_trust_bundle`. 
This PR ensures that if there is a value in the state, do not override value from backend.
Should fix #229

OCM-3124: fix for additional_trust_bundle resulting in an error

---

provider/cluster_rosa_classic_resource.go

We must allow null default values in order to allow using modules for this provider.
When created a module, which sets the `availability_zones = null`
I got an error during destroy that this attribute can't be changed

Allow using empty default value (null) for availability_zones

---

internal/ocm/resource/cluster.go
internal/ocm/resource/cluster_test.go
subsystem/cluster_resource_rosa_test.go

Change the terraform provider logic to align with the logic in the backend
The following cases are allowed:
1. private cluster with private link
2. public cluster without private link
3. private cluster without private link
Public cluster with private link is not allowed

OCM-3005: Fix allow private cluster without private link

---

provider/machinepool/machine_pool_resource.go
subsystem/machine_pool_resource_test.go

- This fixes the problem of TF deciding the machine pool needs to be replaced unnecessarily.
- There is a change here where az and subnet will now have empty ("") values instead of null. This is necessary in order for UseStateForUnknown to allow us to avoid replacing due to (known after apply).
- It adds some static validation of parameters, but isn't really able to remove much of the run-time validation because it depends on the state of the cluster.
- Added some static validation for a couple other parameters

Fix machine pool validation

---

provider/clusterrosaclassic/cluster_rosa_classic_resource.go
provider/proxy/proxy_validator.go
subsystem/cluster_resource_rosa_test.go

Currently if you try to remove param from proxy you will fail as nothing actually is sent to ocm,
same if you try to remove full proxy object. 
This change will send proxy params as empty string in case they were deleted

Fix update proxy in cluster rosa

---

tests/e2e/idps_test.go
tests/e2e/init_test.go
tests/tf-manifests/rhcs/idps/htpasswd/main.tf
tests/tf-manifests/rhcs/idps/htpasswd/output.tf
tests/tf-manifests/rhcs/idps/htpasswd/variables.tf
tests/utils/constants/constants.go
tests/utils/exec/idps.go
tests/utils/exec/openshift.go

Test case automated: [OCP-63151](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-63151)
passing result:

add htpasswd test and expanding current IDP infrastructure- automating ocp63151

---

.github/workflows/check-pull-request.yaml
build/ci-tf-e2e.Dockerfile
go.mod
go.sum

The new TF CLI 1.6.0 caused errors of resource/data source types Not Found.
According to [that open issue](https://github.com/hashicorp/terraform-plugin-framework/issues/853):
`This is a Framework bug affecting users of Terraform 1.6 using providers built using Plugin Framework 1.4.0. The root cause is the recent caching functionality being enabled in https://github.com/hashicorp/terraform-plugin-framework/issues/828.`
A workaround for now is downgrading the `terraform-plugin-framework` version (from 1.4.0 to 1.3.5) and also the `terraform-plugin-go` (from 0.19.0 to 0.18.0)

Downgrade framework version because of an issue caused by the new version of the TF CLI 1.6.0

---

docs/index.md
templates/index.md.tmpl

To see how the changes applies in the terraform docs you can copy it to the preview tool:
https://registry.terraform.io/tools/doc-preview
Removed all limitations
The following limitations relevant to specific attributes or resources and need to move to the specific doc:
```
* When creating a machine pool, you need to specify your replica count. You must define either the `replicas= "<count>"` variable or provide values for the following variables to build the machine pool:
* `min_replicas = "<count>"`
* `max_replicas="<count>"`
* `autoscaling_enabled=true`
* The htpasswd identity provider does not support creating the identity provider with multiple users or adding additional users to the existing identity provider.
* The S3 bucket that is created as part of the OIDC configuration must be …
```

OCM-4303: Fix main doc

---

tests/README.md
tests/ci/profile_handler.go
tests/ci/profiles/tf_cluster_profile.yml
tests/e2e/e2e_suite_test.go
tests/e2e/idps_test.go
tests/e2e/verfication_post_day1_test.go
tests/utils/constants/config.go
tests/utils/constants/constants.go
tests/utils/exec/cluster.go
tests/utils/helper/helper.go

**PR changes:**
- 6 new verification tests added for testing post cluster creation 
- `FIPS`, `Etcd`, `Autoscale`, `ComputeMachineType` attributes were added 
- Getter/Setter for `clusterID` and `token` inside the test suite
- Test case coverage:` OCP-63140, OCP-63133, OCP-63143, OCP-64023, OCP-63141, OCP-68423`

Add post day 1 verification tests

---

docs/resources/cluster_rosa_classic.md
docs/resources/machine_pool.md
internal/ocm/resource/cluster.go
internal/ocm/resource/cluster_test.go
provider/clusterrosaclassic/cluster_rosa_classic_resource.go
provider/clusterrosaclassic/cluster_rosa_classic_state.go
provider/machinepool/machine_pool_resource.go
provider/machinepool/machine_pool_state.go
subsystem/cluster_resource_rosa_test.go
subsystem/machine_pool_resource_test.go

- [OCM-2641](https://issues.redhat.com//browse/OCM-2641): Adds `worker_disk_size` to cluster resource. This is used only at cluster creation to determine the size of the default MP's disk size
- [OCM-17](https://issues.redhat.com//browse/OCM-17): Adds `disk_size` to the machinepool resource. -- Only used at pool creation time
Supersceedes #100

OCM-2641, OCM-17: Specify worker disk size for machine pools

---

provider/clusterrosaclassic/cluster_rosa_classic_resource.go
provider/clusterrosaclassic/cluster_rosa_classic_resource_test.go
provider/machinepool/machine_pool_resource.go
subsystem/cluster_resource_rosa_test.go
subsystem/machine_pool_resource_test.go

OCM-3042: Default MachinePool should be manipulated via machine_pool resource

---

provider/machinepool/machine_pool_resource.go

The "magic import" of the day-1 worker pool was not storing the result of the resource update operation, and so values were not being properly populated, specifically disk size.

Store the correct state during worker pool import

---

provider/common/immutable_modifier.go

This replaces the old ValueCannotBeChanged modifier that existed before the framework upgrade. This modifier will only allow an attribute's value to be set during the initial creation of the containing resource. After that, any attempt to change the attribute will result in an error.
This modifier should be viewed as an alternative to the RequiresReplace modifier where we would rather return an error to the user than cause the resource to be recreated.
The modifier cannot be used on a "computed" attribute because computed attributes may get assigned values that are not present in the configuration.
It also does not permit "unknown" values (after the initial create) since they cannot be validated.

Add a PlanModifier to indicate an attribute is immutable.

---

tests/e2e/cluster_destroy_test.go
tests/e2e/idps_test.go
tests/utils/constants/config.go

When there is an ENV variable `KUBECONFIG`set and then try to login with `oc` command at the same time file path of `KUBECONFIG` not existing, it will cause warning of config not found. 
This PR enhanced the oc login command to make it redirect the kubeconfig path to an indicated file rather than using global `KUBECONFIG` env.
There will be a dir `$RHCS_OUTPUT/kubeconfig` created when run the tests, and it will be destroyed in destroy step(This is for clean local env. In prow, folders will be skipped when update $SHARE_DIR secret dir.)

Enhance the oc login command to kill no kubeconfig warning in prow

---

tests/e2e/machine_pool_test.go

OCP-65063 Create single-az machinepool for multi-az cluster"
The test passed on local
Ran 1 of 21 Specs in 18.502 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 20 Skipped
PASS
Ginkgo ran 1 suite in 21.295953125s
amalykhi@amalykhi-mac terraform-provider-rhcs % ginkgo run --focus OCP-65063 ./tests/e2e

small fix for mp test

---

provider/identityprovider/openid.go
subsystem/identity_provider_resource_test.go

cannot reflect tftypes.List[tftypes.String] into a map, must be a map

OCM-4779: Fixing error in openid IDP

---

tests/e2e/idps_test.go
tests/tf-manifests/rhcs/idps/github/main.tf
tests/tf-manifests/rhcs/idps/github/variables.tf
tests/tf-manifests/rhcs/idps/gitlab/main.tf
tests/tf-manifests/rhcs/idps/ldap/main.tf
tests/tf-manifests/rhcs/idps/ldap/variables.tf
tests/utils/exec/idps.go

This PR will validate all the mandatory fields each idp resource has, as described in the[ terraform rhcs provider doc](https://registry.terraform.io/providers/terraform-redhat/rhcs/latest/docs/resources/identity_provider)

add idp negative tests - validate mandatory fields

---

tests/e2e/machine_pool_test.go
tests/tf-manifests/aws/vpc-tags/main.tf
tests/tf-manifests/aws/vpc-tags/variables.tf
tests/utils/constants/constants.go
tests/utils/exec/tf-exec.go
tests/utils/exec/vpc-tags.go

Singleaz test ocp-65063
the test passed after the fix
Ran 1 of 24 Specs in 27.974 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 23 Skipped
PASS
Ginkgo ran 1 suite in 28.970285431s
[amalykhi@amalykhi-thinkpadp1gen5 terraform-provider-rhcs]$ ginkgo run --focus OCP-65071 --timeout 2h --output-dir /tmp/secret --junit-report result.xml -r --focus-file tests/e2e/. tests/e2e/..

single-az machinepool tc

---

tests/ci/profile_handler.go
tests/ci/profiles/tf_cluster_profile.yml
tests/e2e/verfication_post_day1_test.go
tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
tests/utils/constants/constants.go
tests/utils/exec/cluster.go
tests/utils/helper/helper.go

OCP-65928 - [tf] [OCM-2674](https://issues.redhat.com//browse/OCM-2674) - Cluster admin during deployment - confirm user created ONLY during cluster creation operation
time="2023-11-26T12:45:49+02:00" level=info msg="[>>] Running CMD: oc login https://api.rhcs-sts-ad-ldi.6vaq.s1.devshift.org:6443 --username CLUSTER_ADMIN --password <password>"
time="2023-11-26T12:46:00+02:00" level=info msg="Got output Login successful.\n\nYou have access to 102 projects, the list has been suppressed. You can list all projects with 'oc projects'\n\nUsing project \"default\".\nWelcome! See 'oc help' to get started."
•SSSSSSSSSSSSSS
Ran 1 of 23 Specs in 12.780 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 22 Skipped
PASS
Ginkgo ran 1 suite in 13.546559198s

OCM-4701 Automate OCP-65928 Cluster admin user during deployment 

---

tests/e2e/verfication_post_day1_test.go

As I see in logs
WARNING: Using insecure TLS client config. Setting this option is not supported!
-removing
As experienced with last CI runs - it takes in average 5 minutes to get cluster ready and access oc login command - increased the timeout

insecure-skip-tls-verify and timeout fix

---

tests/e2e/verfication_post_day1_test.go

What I have done in this PR:
Exclude @OCP-65928 from CI run until we figure out how to make oc command not affected by cluster status too much

Exclude @OCP-65928 from CI run

---

tests/ci/profiles/tf_cluster_profile.yml

Error https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/46462/rehearse-46462-pull-ci-terraform-redhat-terraform-provider-rhcs-v1.4.0-branch-rosa-sts-advanced-critical-high-presubmit/1734178562728005632/artifacts/rosa-sts-advanced-critical-high-presubmit/rhcs-e2e-setup/build-log.txt
Creation complete after 1s [id=eipalloc-0353722ac0c8921f2]\nmodule.vpc.aws_default_security_group.this[0]: Creation complete after 2s [id=sg-0d2c5d14f040fd1a3]\nmodule.vpc.aws_route.public_internet_gateway[0]: Creation complete after 1s [id=r-rtb-0752f0a09f046d20a1080289494]\nmodule.vpc.aws_default_network_acl.this[0]: Creation complete after 2s [id=acl-0abacabb6cba56bbf]\n\nError: creating EC2 Subnet: InvalidParameterValue: Value (ap-northeast-1b) for …

V1.4.0 zone fix - remove hardcoded AZones

---

tests/ci/labels.go
tests/ci/profile_handler.go
tests/e2e/cluster_destroy_test.go
tests/e2e/machine_pool_test.go
tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
tests/tf-manifests/rhcs/default-machine-pool/main.tf
tests/tf-manifests/rhcs/default-machine-pool/output.tf
tests/tf-manifests/rhcs/default-machine-pool/variable.tf
tests/utils/constants/constants.go
tests/utils/exec/account-roles.go
tests/utils/exec/cluster.go
tests/utils/exec/dns-domain.go
tests/utils/exec/idps.go
tests/utils/exec/machine-pools.go
tests/utils/exec/oidc-provider-operator-roles.go
tests/utils/exec/rhcs-info.go
tests/utils/exec/security-groups.go
tests/utils/exec/tf-exec.go
tests/utils/exec/vpc-tags.go
tests/utils/exec/vpc.go
tests/utils/helper/helper.go
tests/utils/helper/tf_helper.go

- new automated 69073 69009 69727
- Add default-machine-pool folder for testing
- Add default machinepool resource "rhcs_machine_pool":"dmp"
- Add MachinePoolService.Plan function for runming `terraform plan` and add output as the return value for Create/Destroy function
- Add functions to build default machinepool arguments from the cluster/default machinepool state 
- Add two helper functions in tf_helper.go
I comment out the day-0 test case until there is day-0 job. Testing on local is passed.
Here are logs bellow:
`
yuwan1-mac:terraform-provider-rhcs yuwan$ ginkgo --focus @OCP-69073 ./tests/e2e/
time="2023-12-05T20:29:11+08:00" level=info msg="Running against env staging with gateway url https://api.stage.openshift.com"
time="2023-12-05T20:29:11+08:00" level=info msg="Loaded cluster …

new automated 69073 69009 69727 and some updates

---

tests/e2e/verfication_post_day1_test.go
tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf

Polarion test case - https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-64906
custom_properties that are checked: custom_property, rosa_tf_version, rosa_tf_commit

Automate OCP-64906 :: Verify custom properties are set post cluster creation

---

provider/cluster/cluster_resource.go
provider/clusterrosaclassic/cluster_rosa_classic_resource.go
provider/machinepool/machine_pool_resource.go

Related issue: [OCM-5233](https://issues.redhat.com//browse/OCM-5233)
Immutable doesn't allow updates to the state even though we are not really updating or tracking this in the state at all

OCM-5233 | fix: remove immutable from compute SGs

---

tests/e2e/idps_test.go
tests/e2e/verfication_post_day1_test.go

Test case: https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-65684 
I noticed that there are parts of this specific test case that cannot be automated, are complicated and also interfere with other automated test cases that will run after (such as destroying the resource), hence, this test case will test the process of importing the cluster and checking the operation was successful. 
the negative part of this test will be automated on a separate PR.
we can open a discussion on that if there are other opinions ofcourse :)

add rhcs_rosa_classic cluster import test case

---

tests/e2e/verfication_post_day1_test.go

this test would be refactored to contain more checks after importing.
for now deleting this line, since causing CI failures

remove version check from ocp65684

---

provider/kubeletconfig/kubeletconfig_validators.go
provider/kubeletconfig/kubeletconfig_validators_test.go

This PR updates the validator for the `pod_pids_limit` field of `KubeletConfig` to defer validation when the value is currently unknown or null. 
`null` values are handled by TF itself with a much clearer error message. `unknown` values are possible during the `configure` method of the provider when the value is set via a variable, see: https://developer.hashicorp.com/terraform/plugin/framework/handling-data/accessing-values#when-can-a-value-be-unknown-or-null

OCM-5345 | fix: Allow pod_pids_limit to be set via a variable

---

tests/ci/profile_handler.go
tests/ci/profiles/tf_cluster_profile.yml
tests/e2e/verfication_post_day1_test.go
tests/tf-manifests/aws/account-roles/main.tf
tests/tf-manifests/aws/account-roles/variables.tf
tests/tf-manifests/aws/oidc-provider-operator-roles/main.tf
tests/tf-manifests/aws/oidc-provider-operator-roles/variables.tf
tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
tests/utils/exec/account-roles.go
tests/utils/exec/cluster.go
tests/utils/exec/oidc-provider-operator-roles.go

Ran 1 of 44 Specs in 1.704 seconds
SUCCESS! -- 1 Passed | 0 Failed | 1 Pending | 42 Skipped
PASS
Ginkgo ran 1 suite in 2.954991039s
https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-63138
https://issues.redhat.com/browse/OCM-4483

OCM-4483: add unified_ path for account/operator case

---

provider/common/cluster_waiter.go
provider/kubeletconfig/kubeletconfig_resource.go

This PR updates the cluster wait functions to ensure that we only wait for a cluster that is in a state that can become `ready`. A cluster that is in a state `error` or `uninstalling` will never become `ready` and we can shortcut the waiting function.

OCM-5346 | fix: Do not wait for clusters in terminal states to be ready

---

tests/e2e/idps_test.go
tests/e2e/verfication_post_day1_test.go
tests/tf-manifests/rhcs/resource-import/main.tf

Adding negative scenarios to the terraform import feature.
**rosa-classic import execution** ([OCP-65684](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-65684)):
<br></br>
**idp import execution** ([OCP-65981](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-65981)):

add import negative tests

---

provider/clusterrosaclassic/cluster_rosa_classic_resource.go
provider/machinepool/machine_pool_resource.go
subsystem/machine_pool_resource_test.go

This PR changes "validate No Immutable Attribute Change" validation to be done also from "magicImport" function (for worker/default machine pool).
In order to allow this, need to consider also unknow plan attributes, because "magicImport" is done as part of the "Create" function, in which it possible.
This change also fixes: [OCM-5408](https://issues.redhat.com/browse/OCM-5408)

OCM-5407: Validate Immutable attributes not changed after magic import

---

provider/machinepool/machine_pool_resource.go
subsystem/machine_pool_resource_test.go

If users wish to delete all labels, they should simply remove the `labels` attribute from the tf statement.

OCM-5285: MP labels can't be an empty map

---

tests/utils/helper/helper.go

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/terraform-redhat_terraform-provider-rhcs/467/pull-ci-terraform-redhat-terraform-provider-rhcs-main-rosa-sts-advanced-optional-critical-high-presubmit/1741418998823653376
I found out from the CI results that simetimes the symbols/numbers are missed in the string
nAttribute admin_credentials.password password must contain numbers or\nsymbols, got: lJoEKrgzbcWnJG",

Fix random string with symbols function

---

provider/machinepool/machine_pool_resource.go
subsystem/machine_pool_resource_test.go

This fixes an inconsistent result from the provider when attempting to delete taints by passing an empty array.

OCM-3021: MP taints can't be an empty array

---

tests/ci/profile_handler.go
tests/e2e/negative_day_one_test.go
tests/utils/exec/cluster.go

There are cases where deleting terraform.tfvars when facing an error in the cluster is something we would like to prevent -
for example, when we have negative scenarios, we would like the original vars to exists and not get deleted by the test.
The PR opened as a solution for one of the tests described in this [PR](https://github.com/terraform-redhat/terraform-provider-rhcs/pull/476)

Add an option to prevent terraform.tfvars deletion

---

tests/e2e/cluster_creation_test.go
tests/e2e/e2e_suite_test.go
tests/e2e/idps_test.go
tests/e2e/machine_pool_test.go
tests/e2e/verfication_post_day1_test.go
tests/tf-manifests/rhcs/default-machine-pool/variable.tf
tests/utils/constants/config.go
tests/utils/constants/constants.go
tests/utils/helper/manifests_handler.go

What I did in this PR:
- Support RHCS_SOURCE AND RHCS_VERSION env variables to replace all of source/version for the manifests files
-  Fixed @OCP-69144 And @OCP-69146 with latest code change
- Enhanced operator waiting for cluster preparation, once local user has no access to /credentials endpoint will return directly with a warning reported
The fixed log and running case with ENV set to `RHCS_VERSION="1.5.0-prerelease.2"` and `RHCS_SOURCE="terraform-redhat/rhcs"`
```
lixue@Xue-Lis-MacBook-Pro terraform-provider-rhcs % ginkgo -focus "(@OCP-69144|@OCP-69146)" tests/e2e
time="2023-12-29T19:16:44+08:00" level=info msg="Running against env staging with gateway url https://api.stage.openshift.com"
time="2023-12-29T19:16:44+08:00" level=info msg="Loaded cluster profile configuration from …
```

Support RHCS_SOURCE and RHCS_VERSION for CI jobs

---

provider/defaultingress/ingress.go
subsystem/default_ingress_resource_test.go

Related issue: [OCM-5406](https://issues.redhat.com//browse/OCM-5406)

OCM-5406 | fix: set att to empty if removed from plan

---

tests/e2e/idps_test.go

fix OCP-65981 :: change expected error syntax when no clusterID exists 

---

tests/ci/profile_handler.go
tests/e2e/general_day_two_test.go
tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
tests/utils/constants/profile_defaults.go
tests/utils/exec/cluster.go
tests/utils/exec/tf-exec.go
tests/utils/helper/helper.go

Automation test case : [OCP-64907](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-64907)
The test purpose is to validate custom property operations on cluster - such as adding, deleting, editing custom property to an existing cluster.
Depends on this [PR](https://github.com/terraform-redhat/terraform-provider-rhcs/pull/477).

automate ocp-64907 :: validate custom property operations on cluster 

---

tests/e2e/idps_test.go

small addition functionality to the idp import test

add the option to destroy import idp resources

---

tests/ci/profile_handler.go
tests/utils/constants/config.go
tests/utils/constants/profile_defaults.go

The new custom property - QE_USAGE, will help us to track after leakages by indicating the name of
the profile from which the cluster was created and did not teardown.
Depends on this [PR](https://github.com/openshift/release/pull/47237)

add qe_usage var env to track leakages

---

tests/e2e/verfication_post_day1_test.go

Following this thread: https://redhat-internal.slack.com/archives/C063JMV5SEP/p1704776239261739

exclude OCP-65684 from CI until fixed

---

tests/utils/constants/config.go
tests/utils/constants/constants.go
tests/utils/constants/profile_defaults.go

qe_usage was returned empty since it was placed in the wrong files. 
after re-testing, seems to work now:
```
$ ocm get cluster 28mmm599tf8d8vvk1hueprpdpjo4ogp2 | grep qe
"qe_usage": "rosa-sts-advanced-critical-high-f3-try"
```

change the place of qe_usage property

---

provider/common/tfconversions.go
provider/defaultingress/ingress.go
subsystem/default_ingress_resource_test.go

Related issue: [OCM-5425](https://issues.redhat.com//browse/OCM-5425)
Only sends the value if the plan is actually different from the state which reveals an actual intention to adjust those attributes
TF provider always sent default values even when not required. Because the API responds by validating each attribute individually it would always respond that the `Route selector` attribute is invalid as it's the first one to be validated.

OCM-5425 | fix: do not set default values if not supplied

---

tests/e2e/verfication_post_day1_test.go
tests/utils/constants/constants.go
tests/utils/helper/manifests_handler.go

`defer h.DeleteFile(con.GrantTFstateFile(con.ImportResourceDir))`
this will delete the state file after importing the rosa sts cluster, and after that we can run other machine-pool/idp import cases without issues.

Fix OCP-65684 :: remove state file to prevent destructive import

---

provider/defaultingress/ingress.go

Currently the actual output looks like 
```
│ Cannont upate default ingress forcluster '28gjcif4b7fluce0uksce104492bjk0h': status is 400 ...
``` 
Expected:
```
Cannot update default ingress for cluster ...
```

fix typo in ingress error message

---

.github/pull_request_template.md
.github/workflows/check-commit-format.yml
CONTRIBUTE.md

Add more details about the TYPE options
Fixes #[OCM-5422](https://issues.redhat.com//browse/OCM-5422)
**Checklist**

OCM-5422: Make the commit format more clear

---

build/build_multiarch

SHA256SUM file needs a column with each filename of the release.
We were adding the full path and it breaks the Hashicorp release sync.

OCM-4953 | fix: remove paths from SHA256SUM releases

---

.github/workflows/check-commit-format.yml

This is done for exclude commits in auto generated PRs Now added commit message from red-hat-konflux
**Which issue(s) this PR fixes**:
Fixes #[OCM-5853](https://issues.redhat.com//browse/OCM-5853)
**Checklist**

OCM-5853: exclude commits validations for PRs created by specific authors

---

tests/e2e/verfication_post_day1_test.go

Post-day1 test to validate proxy deployment - based on this test case:: [OCP-67607](https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-67607)

OCM-6007 | ci: validate proxy post cluster creation

---

tests/tf-manifests/aws/proxy/main.tf

This will prevent error messages "already exists" for imported-key-pair name in case they are not deleted (leftovers).

OCM-5698 | ci: fix key-pair name duplication

---

tests/e2e/verfication_post_day1_test.go

We had issues with the optional job for rhcs-sts-pl clusters - since the machine_pool_test.go is running before the verification post day1 tests, test case OCP-65071 changes the number of subnets the cluster's vpc have.
hence, the post day1 test case OCP-63141, which validates availability zones and multi-az are set post cluster creation fails, as it reads the current state which was not cleaned after the first test.
In this PR, I have changed OCP-63141 test to not be depended on the results of OCP-65071.

OCM-4331 | ci: fix OCP-63141 to prevent CI failure

---

tests/ci/profile_handler.go
tests/e2e/verfication_post_day1_test.go
tests/utils/exec/tf-exec.go
tests/utils/log/constants.go
tests/utils/log/logger.go

The log of CI job contains sensitive information which should be hidden.
Fixes #[OCM-5551](https://issues.redhat.com/browse/OCM-5551) Hide the sensitive information in terraform automation log
**Checklist**
**Current output**
```
lixue@Xue-Lis-MacBook-Pro terraform-provider-rhcs % ginkgo run --label-filter day1-prepare tests/e2e --timeout 2h     
time="2024-02-23T22:33:18+08:00" level=info msg="Running against env staging with gateway url https://api.stage.openshift.com"
time="2024-02-23T22:33:18+08:00" level=info msg="Loaded cluster profile …
```

OCM-5551 | ci: Hide the sensitive information in terraform automation log

---

tests/ci/profile_handler.go
tests/ci/profiles/tf_classic_cluster_profiles.yml
tests/ci/profiles/tf_hcp_cluster_profiles.yml
tests/e2e/verfication_post_day1_test.go
tests/tf-manifests/rhcs/clusters/rosa-classic/main.tf
tests/tf-manifests/rhcs/clusters/rosa-classic/variables.tf
tests/utils/exec/cluster.go

@xueli181114 PTAL
```
$ ginkgo -focus 63950 tests/e2e                                                              
time="2024-03-15T10:56:25+08:00" level=info msg="Running against env staging with gateway url https://api.stage.openshift.com"
time="2024-03-15T10:56:25+08:00" level=info msg="Loaded cluster profile configuration from profile rosa-sts-pl : map[admin_enabled:false autoscale:false byok:false byovpc:true ccs:true channel_group:candidate cloud_provider:aws cluster_type:rosa-classic compute_machine_type:m5.xlarge etcd_encryption:false fips:false imdsv2:optional kms_key_arn:false labeling:false major_version:4.14 multi_az:false oidc_config:managed private:true private_link:true product_id:rosa proxy:false region:us-east-1 sts:true tagging:false unified_acc_role_path: version: …
```

OCM-902: Verify imdsv2 value is set post cluster creation

---

docs/resources/tuning_config.md
provider/tuningconfigs/resource.go

[OCM-7020](https://issues.redhat.com//browse/OCM-7020)
**Checklist**

OCM-7020 | fix: tuning config id should be computed only

---

tests/ci/labels.go
tests/e2e/cluster_autoscaler_day2_test.go
tests/tf-manifests/rhcs/cluster-autoscaler/main.tf
tests/tf-manifests/rhcs/cluster-autoscaler/output.tf
tests/tf-manifests/rhcs/cluster-autoscaler/variable.tf
tests/utils/cms/cms.go
tests/utils/constants/manifests.go
tests/utils/exec/cluster-autoscaler.go

@xueli181114 PTAL
```
$ ginkgo -focus OCP-69137 tests/e2e                                                                                                         
Ginkgo detected a version mismatch between the Ginkgo CLI and the version of Ginkgo imported by your packages:
Ginkgo CLI Version:
2.9.1
Mismatched package versions found:
2.13.2 used by e2e
Ginkgo will continue to attempt to run but you may see errors (including flag
parsing errors) and should either update your go.mod or your version of the
Ginkgo CLI to match.
To install the matching version of the CLI run
go install github.com/onsi/ginkgo/v2/ginkgo
from a path that contains a go.mod file.  Alternatively you can use
go run github.com/onsi/ginkgo/v2/ginkgo
from a path that contains a go.mod file to invoke the matching version …
```

OCPQE-18948 | ci: Create cluster autoscaler with ocm terraform provider

---

docs/data-sources/cluster_rosa_classic.md
docs/data-sources/cluster_rosa_hcp.md
docs/resources/cluster_rosa_classic.md
docs/resources/cluster_rosa_hcp.md
go.mod
provider/cluster/cluster_resource.go
provider/cluster/cluster_resource_test.go
provider/cluster/cluster_state.go
provider/clusterrosa/classic/cluster_rosa_classic_datasource.go
provider/clusterrosa/classic/cluster_rosa_classic_resource.go
provider/clusterrosa/classic/cluster_rosa_classic_resource_test.go
provider/clusterrosa/classic/cluster_rosa_classic_state.go
provider/clusterrosa/common/consts.go
provider/clusterrosa/hcp/datasource.go
provider/clusterrosa/hcp/resource.go
provider/clusterrosa/hcp/resource_test.go
provider/clusterrosa/hcp/state.go
subsystem/cluster_resource_rosa_create_test.go
subsystem/cluster_resource_rosa_import_test.go
subsystem/cluster_resource_test.go
subsystem/cluster_waiter_test.go
subsystem/hcp/cluster_resource_test.go
subsystem/identity_provider_resource_test.go

The changes allow customer to supply a name which can be less than <= 54 characters and a domain_prefix optional field to customise the cluster's domain.
**Which issue(s) this PR fixes**:
Fixes #[OCM-6148](https://issues.redhat.com//browse/OCM-6148)
**Checklist**

OCM-6148 | feat: allow longer cluster names

---

provider/autoscaler/classic/resource.go
provider/autoscaler/hcp/resource.go
provider/clusterwaiter/cluster_waiter_resource.go
provider/defaultingress/classic/resource.go
provider/defaultingress/hcp/resource.go
provider/group/groups_data_source.go
provider/groupmembership/group_membership_resource.go
provider/identityprovider/identity_provider_resource.go
provider/kubeletconfig/kubeletconfig_resource.go
provider/machinepool/classic/machine_pool_datasource.go
provider/machinepool/classic/machine_pool_resource.go
provider/machinepool/hcp/machine_pool_datasource.go
provider/machinepool/hcp/machine_pool_resource.go
provider/tuningconfigs/resource.go
subsystem/cluster_autoscaler_resource_test.go
subsystem/cluster_waiter_test.go
subsystem/default_ingress_resource_test.go
subsystem/group_membership_resource_test.go
subsystem/groups_data_source_test.go
subsystem/hcp/cluster_autoscaler_resource_test.go
subsystem/hcp/default_ingress_resource_test.go
subsystem/hcp/machine_pool_resource_test.go
subsystem/hcp/tuningconfigs_test.go
subsystem/identity_provider_resource_test.go
subsystem/kubeletconfig_resource_test.go
subsystem/machine_pool_resource_test.go

[OCM-7082](https://issues.redhat.com//browse/OCM-7082)
**Checklist**

OCM-7082 | fix: validate cluster id is not empty for subresources

---

docs/resources/hcp_machine_pool.md
provider/machinepool/hcp/aws_node_pool.go
provider/machinepool/hcp/machine_pool_resource.go
subsystem/hcp/machine_pool_resource_test.go

[OCM-6885](https://issues.redhat.com//browse/OCM-6885)
Relies on parameter to fetch user tags only, excluding system tags the customer might not know about. This helps in making sure that customer is able to provide all cluster plus new machine tags within the management file
**Checklist**

OCM-6885 | fix: should not allow to edit tags on mp of HCP

---

go.mod
go.sum
tests/ci/labels.go
tests/e2e/account_roles_test.go
tests/e2e/classic_machine_pool_test.go
tests/e2e/cluster_autoscaler_day2_test.go
tests/e2e/cluster_misc_day2_test.go
tests/e2e/cluster_upgrade_test.go
tests/e2e/hcp_machine_pool_test.go
tests/e2e/idps_test.go
tests/e2e/kubelet_config_test.go
tests/e2e/negative_day_one_test.go
tests/e2e/verfication_post_day1_test.go
tests/tf-manifests/rhcs/clusters/rosa-classic/output.tf
tests/tf-manifests/rhcs/clusters/rosa-hcp/output.tf
tests/utils/exec/cluster.go
tests/utils/exec/machine-pools.go
tests/utils/exec/tf-exec.go
tests/utils/exec/vpc.go
tests/utils/helper/assert.go
tests/utils/helper/helper.go
tests/utils/helper/map.go

Implement day2 test cases
<details>
<summary>72504</summary>
$ ginkgo -focus 72504 tests/e2e/
time="2024-04-04T16:44:09+02:00" level=info msg="Running against env staging with gateway url https://api.stage.openshift.com"
time="2024-04-04T16:44:09+02:00" level=info msg="Loaded cluster profile configuration from profile rosa-hcp-ad : map[admin_enabled:false autoscale:true byok:true byovpc:true channel_group:candidate cloud_provider:aws cluster_type:rosa-hcp compute_machine_type:m5.2xlarge etcd_encryption:true fips:false kms_key_arn:true labeling:false major_version:4.15 multi_az:true oidc_config:managed private:false product_id:rosa proxy:true region:us-west-2 sts:true tagging:true unified_acc_role_path: version: version_pattern:latest zones:a,b,c]" …

OCM-7141 | ci: Automate 72451/72504/72505/72507/72509/72510

---

tests/tf-manifests/aws/proxy/main.tf

[OCM-7534](https://issues.redhat.com//browse/OCM-7534) | ci: Replace deprecated proxy image

OCM-7534 | ci: Replace deprecated proxy image

---

docs/data-sources/hcp_policies.md
docs/data-sources/policies.md
provider/ocm_policies/classic/ocm_policies_data_source.go
provider/ocm_policies/classic/ocm_policies_state.go
provider/ocm_policies/common/rh_support_role.go
provider/ocm_policies/hcp/ocm_policies_data_source.go
provider/ocm_policies/hcp/ocm_policies_state.go
subsystem/hcp/rosa_ocm_policies_data_source_test.go
subsystem/rosa_ocm_policies_data_source_test.go

[OCM-7493](https://issues.redhat.com//browse/OCM-7493)
The isolated support role (org based) is generated from the /sts_policies API, the API fetches the whole trust policy details. However, as TF is generating the trust policy details by itself this role is not being set as the principal. This needs to be adjusted so that it is possible to attach the isolated support role.
This PR fetches the details and parses the role so that it is possible to insert it in the trust policy generated by the module
**Checklist**

OCM-7493 | fix: allow datasource to fetch isolated support role

---

tests/e2e/hcp_machine_pool_test.go
tests/e2e/tuning_config.go

<details>
<summary>72510</summary>
Will run 1 of 78 specs
time="2024-04-26T10:37:32+02:00" level=info msg="Loaded cluster profile configuration from profile rosa-hcp-ad : map[admin_enabled:false autoscale:true byok:true byovpc:true channel_group:candidate cloud_provider:aws cluster_type:rosa-hcp compute_machine_type:m5.2xlarge compute_replicas:6 etcd_encryption:true fips:false kms_key_arn:true labeling:false major_version:4.15 multi_az:true oidc_config:managed private:false product_id:rosa proxy:true region:us-west-2 sts:true tagging:true unified_acc_role_path:/advanced/ version: version_pattern:latest zones:a,b,c]"
time="2024-04-26T10:37:32+02:00" level=info msg="Running terraform init against the dir /home/tradisso/projects/openshift/terraform-provider-rhcs/tests/tf-manifests/rhcs/cluste …

OCM-7648 | ci: Fix HCP c/h tests

---

tests/ci/profile_handler.go
tests/e2e/cluster_edit_test.go
tests/tf-manifests/rhcs/clusters/rosa-hcp/output.tf
tests/utils/exec/cluster.go

<details>
<summary>Logs</summary>
Will run 1 of 88 specs
time="2024-04-29T11:23:55+02:00" level=info msg="Loaded cluster profile configuration from profile rosa-hcp-ad : map[admin_enabled:false autoscale:true byok:true byovpc:true channel_group:candidate cloud_provider:aws cluster_type:rosa-hcp compute_machine_type:m5.2xlarge compute_replicas:6 etcd_encryption:true fips:false kms_key_arn:true labeling:false major_version:4.15 multi_az:true oidc_config:managed private:false product_id:rosa proxy:true region:us-west-2 sts:true tagging:true unified_acc_role_path:/advanced/ version: version_pattern:latest zones:a,b,c]"
time="2024-04-29T11:23:55+02:00" level=info msg="Running terraform init against the dir /home/tradisso/projects/openshift/terraform-provider-rhcs/tests/tf-manifests/rhcs/cluster …

OCM-7141 | ci: Automate 72628

---

tests/e2e/cluster_edit_test.go

<details>
<summary>Logs</summary>
Will run 1 of 101 specs
time="2024-05-03T11:45:16+02:00" level=info msg="Loaded cluster profile configuration from profile rosa-hcp-ad : map[admin_enabled:false autoscale:true byok:true byovpc:true channel_group:candidate cloud_provider:aws cluster_type:rosa-hcp compute_machine_type:m5.2xlarge compute_replicas:6 etcd_encryption:true fips:false kms_key_arn:true labeling:false major_version:4.15 multi_az:true oidc_config:managed private:false product_id:rosa proxy:true region:us-west-2 sts:true tagging:true unified_acc_role_path:/advanced/ version: version_pattern:latest zones:a,b,c]"
time="2024-05-03T11:45:16+02:00" level=info msg="Running terraform init against the dir /home/tradisso/projects/openshift/terraform-provider-rhcs/tests/tf-manifests/rhcs/cluste …

OCM-6805 | ci: Update 72452 (edit billing account)

---

tests/e2e/cluster_edit_test.go

<details>
<summary>Logs</summary>
Will run 1 of 101 specs
time="2024-05-03T14:38:50+02:00" level=info msg="Loaded cluster profile configuration from profile rosa-hcp-ad : map[admin_enabled:false autoscale:true byok:true byovpc:true channel_group:candidate cloud_provider:aws cluster_type:rosa-hcp compute_machine_type:m5.2xlarge compute_replicas:6 etcd_encryption:true fips:false kms_key_arn:true labeling:false major_version:4.15 multi_az:true oidc_config:managed private:false product_id:rosa proxy:true region:us-west-2 sts:true tagging:true unified_acc_role_path:/advanced/ version: version_pattern:latest zones:a,b,c]"
time="2024-05-03T14:38:50+02:00" level=info msg="Running terraform init against the dir /home/tradisso/projects/openshift/terraform-provider-rhcs/tests/tf-manifests/rhcs/cluste …

OCM-7820 | ci: Update 72487 (edit etcd key)

---

tests/e2e/hcp_machine_pool_test.go
tests/utils/cms/versions.go

<details>
<summary></summary>
Will run 1 of 101 specs
time="2024-05-03T15:41:08+02:00" level=info msg="Loaded cluster profile configuration from profile rosa-hcp-ad : map[admin_enabled:false autoscale:true byok:true byovpc:true channel_group:candidate cloud_provider:aws cluster_type:rosa-hcp compute_machine_type:m5.2xlarge compute_replicas:6 etcd_encryption:true fips:false kms_key_arn:true labeling:false major_version:4.15 multi_az:true oidc_config:managed private:false product_id:rosa proxy:true region:us-west-2 sts:true tagging:true unified_acc_role_path:/advanced/ version: version_pattern:latest zones:a,b,c]"
time="2024-05-03T15:41:08+02:00" level=info msg="Running terraform init against the dir /home/tradisso/projects/openshift/terraform-provider-rhcs/tests/tf-manifests/rhcs/clusters/r …

OCM-7083 | ci: Enable tc 72509 (upgrade np)

---

provider/clusterrosa/common/consts.go
provider/clusterrosa/common/consts_test.go

[OCM-7852](https://issues.redhat.com//browse/OCM-7852) 
**Checklist**

OCM-7852 | fix: allow assumed-role into creator arn property

---

tests/ci/labels.go
tests/e2e/account_roles_test.go
tests/e2e/classic_machine_pool_test.go
tests/e2e/cluster_autoscaler_day2_test.go
tests/e2e/cluster_edit_test.go
tests/e2e/cluster_misc_day2_test.go
tests/e2e/cluster_upgrade_test.go
tests/e2e/dns_test.go
tests/e2e/hcp_ingress_test.go
tests/e2e/hcp_machine_pool_test.go
tests/e2e/kubelet_config_test.go
tests/e2e/negative_day_one_test.go
tests/e2e/tuning_config_test.go
tests/e2e/verification_post_day1_test.go

Remove `NonClassicCluster` and `NonHCPCluster` as the logic is now done into the code itself.
https://issues.redhat.com/browse/OCM-8959
**Checklist**

OCM-8959 | ci: Remove Non*Cluster labels

---

tests/ci/profile_handler.go
tests/e2e/cluster_creation_test.go
tests/e2e/cluster_destroy_test.go
tests/e2e/negative_day_one_test.go

- Remove fail fast error when deleting cluster resources, preventing other resources to be deleted
- Removed some `Expect` usage
https://issues.redhat.com/browse/OCM-8983
**Checklist**

OCM-8983 | ci: Review Profile Handler errors

---

tests/utils/exec/tf-exec.go
tests/utils/helper/file.go

https://issues.redhat.com/browse/OCM-9358
**Checklist**

OCM-9358 | ci: TF destroy should ignore missing tfvars file

---

build/ci-tf-e2e.Dockerfile

`oc` command is failing on CI due to glibc needed by the command line
https://issues.redhat.com/browse/OCM-9457
**Checklist**

OCM-9457 | ci: Fix `oc` command issue on ubi8

---

tests/e2e/classic_machine_pool_test.go
tests/e2e/hcp_machine_pool_test.go
tests/e2e/kubelet_config_test.go
tests/e2e/verification_post_day1_test.go
tests/tf-manifests/rhcs/machine-pools/hcp/main.tf
tests/tf-manifests/rhcs/machine-pools/hcp/output.tf
tests/tf-manifests/rhcs/machine-pools/hcp/variable.tf
tests/tf-manifests/rhcs/resource-import/main.tf
tests/utils/cms/cms.go
tests/utils/cms/versions.go
tests/utils/exec/kubelet-config.go
tests/utils/exec/machine-pools.go
tests/utils/log/logger.go

<details>
<summary>72512</summary>
time="2024-07-01T22:06:30+02:00" level=info msg="Loaded cluster profile configuration from profile rosa-hcp-ad : map[admin_enabled:false autoscale:true byok:true byovpc:true channel_group:candidate cloud_provider:aws cluster_type:rosa-hcp compute_machine_type:m5.2xlarge compute_replicas:6 etcd_encryption:true fips:false kms_key_arn:true labeling:false major_version:4.15 multi_az:true oidc_config:managed private:false product_id:rosa proxy:true region:us-west-2 sts:true tagging:true unified_acc_role_path:/advanced/ version: version_pattern:latest zones:a,b,c]"
time="2024-07-01T22:06:30+02:00" level=info msg="Running terraform init against the dir /home/tradisso/projects/openshift/terraform-provider-rhcs/tests/tf-manifests/rhcs/clusters/rosa-hcp" …

OCM-9263 | ci: Automate ids 72960/72954/72513/72512

---

tests/e2e/kubelet_config_test.go

Fix case failure of 70128
Fixes #
[OCM-9934](https://issues.redhat.com//browse/OCM-9934)
**Checklist**

OCM-9934 | ci: fix failure of 70128

---

tests/README.md

https://issues.redhat.com/browse/OCM-9975
**Checklist**

OCM-9975 | ci: Remove `NonClassicCluster` and `NonHCPCluster` labels

---

provider/defaultingress/classic/resource.go
tests/e2e/classic_ingress_test.go

Set component_routes to empty object will cause provider bug
Fixes #
[OCM-10439](https://issues.redhat.com//browse/OCM-10439)
**Checklist**

OCM-10439 | fix: Set component_routes to empty object will cause provider bug

---

tests/ci/profile_handler.go
tests/e2e/idps_test.go
tests/e2e/verification_post_day1_test.go
tests/utils/constants/config.go
tests/utils/helper/helper.go

Cluster state file cannot be recorded once process terminated. This caused the resource leak in pull requests testing.
Fixes #
[OCM-10607](https://issues.redhat.com//browse/OCM-10607)
**Checklist**

OCM-10607 | ci: fix the cluster leak issue

---

provider/machinepool/classic/machine_pool_resource.go

When creating the default Machinepool, the provider is first importing it as already existing and then performing an update.
One condition was missing in the Populate State, when importing.
https://issues.redhat.com/browse/OCM-10684
**Checklist**

OCM-10684 | ci: Fix tags issue when creating default MP

---

tests/e2e/negative_day_one_test.go
tests/utils/exec/tf-exec.go

In e2e tests, if an error occurs during apply, some resources may have been created already. But the TF vars file is not saved, thus the destroy will not occurs.
This fix is storing the values in a tfvars tmp file and destroy will consider it if existing if the default TF vars file is not existing.
https://issues.redhat.com/browse/OCM-10640
**Checklist**

OCM-10640 | ci: Fix destroy resources if error in apply

---

tests/e2e/hcp_machine_pool_test.go
tests/e2e/tuning_config_test.go
tests/tf-manifests/rhcs/tuning-config/main.tf
tests/tf-manifests/rhcs/tuning-config/variable.tf
tests/utils/exec/tuning-configs.go
tests/utils/helper/file.go
tests/utils/helper/tuningconfig.go

Use yaml for Tuning Config spec
https://issues.redhat.com/browse/OCM-10609
**Checklist**

OCM-10609 | ci: Tuning Configs support yaml

---

CONTRIBUTE.md
provider/defaultingress/hcp/resource.go
provider/machinepool/hcp/machine_pool_resource.go
tests/tf-manifests/aws/shared-vpc-policy-and-hosted-zone/main.tf

warning message is referring to classic on HCP clusters
Improve also a little CONTRIBUTE.md
The tests/ file is due to a run with `terraform format`.
Warning message is misleading
Fixes [OCM-10961](https://issues.redhat.com//browse/OCM-10961)
**Checklist**

OCM-10961 | fix: warning message is referring to classic on HCP clusters

---

docs/data-sources/cluster_rosa_hcp.md
docs/data-sources/hcp_machine_pool.md
docs/resources/cluster_rosa_hcp.md
docs/resources/hcp_machine_pool.md
provider/clusterrosa/hcp/datasource.go
provider/clusterrosa/hcp/resource.go
provider/clusterrosa/hcp/state.go
provider/machinepool/classic/machine_pool_resource.go
provider/machinepool/hcp/aws_node_pool.go
provider/machinepool/hcp/machine_pool_resource.go
subsystem/hcp/cluster_resource_test.go
subsystem/hcp/machine_pool_resource_test.go

- Adds the custom disk size field for creating node pools to the terraform provider, so that node pools with a custom disk size can be created through terraform
- Adds a disk size field to HCP cluster creation so that day 1 node pools w/ custom disk size can be created through terraform
https://issues.redhat.com/browse/OCM-9892
- [ x] New feature
- [ x] Subsystem tests
**Checklist**

OCM-9892 | feat: add root disk size to TF provider

---

provider/common/attrvalidators/conflicts_with_not_empty.go
provider/common/attrvalidators/conflicts_with_not_empty_test.go
provider/common/attrvalidators/main_test.go
provider/common/planmodifiers/redacted_modifier_test.go
provider/registry_config/resource.go
subsystem/hcp/cluster_resource_test.go

As the API is returning empty lists to clear parameters, while null values are not used, we set empty list as default, so this will cover both null values and empty lists in input, as they should behave in the same way.
Add also a custom validator for conflicts as we need to check against not empty list,while the default conflict validator checks only for null values.
Tests added and validated also locally the different cases.
Related: [OCM-11554](https://issues.redhat.com//browse/OCM-11554)
**Checklist**

OCM-11554 | fix: empty list as default value for registry config

---

tests/e2e/cluster_upgrade_test.go

We don't need the duplicate handler, which would bring us in a new TF workspace, here because we want in fact to update the actual account roles
https://issues.redhat.com/browse/OCM-11524
**Checklist**

OCM-11524 | ci: Fix id:63152

---

provider/common/mutex.go
provider/kubeletconfig/kubeletconfig_resource.go

fix https://issues.redhat.com/browse/OCM-11739
Fixes #[OCM-11739](https://issues.redhat.com//browse/OCM-11739)
**Checklist**

OCM-11739 | fix: add lock to guarantee only one kubelet config for classic cluster

---

tests/ci/profiles/tf_classic_cluster_profiles.yml
tests/ci/profiles/tf_hcp_cluster_profiles.yml
tests/e2e/account_roles_test.go
tests/e2e/cluster_upgrade_test.go
tests/e2e/e2e_suite_test.go
tests/utils/constants/constants.go
tests/utils/constants/version.go
tests/utils/profilehandler/file.go
tests/utils/profilehandler/handler.go
tests/utils/profilehandler/profile.go

Simplify the way we set version/channel group in the automation code and let the CI override the configuration when needed
https://issues.redhat.com/browse/OCM-11805
**Checklist**

OCM-11805 | ci: Review version and version pattern usage

---

provider/clusterrosa/classic/cluster_rosa_classic_resource.go
provider/clusterrosa/common/properties.go

[OCM-12050](https://issues.redhat.com//browse/OCM-12050)
This validation enforces only the initial user that created the cluster can update the cluster resources, this is not ideal considering customers can use other users to update it.
For now it will be considered a warning instead and will be evaluated in a new form to be re introduced
**Checklist**

OCM-12050 | fix: warn instead of error rosa_creatorn_arn update validation

---

tests/e2e/hcp_machine_pool_test.go

[OCM-12269](https://issues.redhat.com//browse/OCM-12269) | ci: fix with reducing the number of sg in id:73068

OCM-12269 | ci: fix with reducing the number of sg in id:73068

---

go.mod
go.sum
provider/identityprovider/github.go
tests/e2e/idps_test.go

Fixes [OCM-12442](https://issues.redhat.com/browse/OCM-12442) Adding github hostname validation to terraform
**Checklist**

OCM-12442 | feat: Added github hostname validation

---

docs/data-sources/cluster_rosa_hcp.md
docs/resources/cluster_rosa_hcp.md
internal/ocm/resource/cluster.go
internal/ocm/resource/cluster_test.go
provider/clusterrosa/classic/cluster_rosa_classic_resource.go
provider/clusterrosa/common/validators.go
provider/clusterrosa/hcp/datasource.go
provider/clusterrosa/hcp/resource.go
provider/clusterrosa/hcp/resource_test.go
provider/clusterrosa/hcp/shared_vpc/shared_vpc.go
provider/clusterrosa/hcp/state.go
provider/common/helpers.go
subsystem/hcp/cluster_resource_test.go

[OCM-12837](https://issues.redhat.com//browse/OCM-12837)
**Checklist**

OCM-12837 | feat: support shared vpc attributes in cluster resource

---

tests/e2e/classic_machine_pool_test.go
tests/e2e/cluster_upgrade_test.go
tests/e2e/hcp_machine_pool_test.go
tests/e2e/idps_test.go
tests/tf-manifests/aws/proxy/main.tf
tests/tf-manifests/rhcs/idps/github/main.tf
tests/tf-manifests/rhcs/idps/github/variables.tf

**What this PR does / why we need it**: Fixes OCP-72514, OCP-68939, OCP-63139, and OCP-63152 tests. Also fixes installing a classic cluster with a proxy enabled
Fixes #[OCM-13194](https://issues.redhat.com//browse/OCM-13194)
**Checklist**

Fixing id:72514,id:68939,id:63139,id:63152 and updating proxy image

---

OWNERS

Adds `hunterkepley` to the `OWNERS` file for this repository

OCM-14586 | chore: Add `hunterkepley` to the OWNERS file

---

docs/resources/hcp_cluster_autoscaler.md
provider/autoscaler/hcp/resource.go
provider/autoscaler/hcp/state.go
subsystem/hcp/cluster_autoscaler_resource_test.go

Allows editing of HCP cluster global autoscaler from TF
Fixes #[OCM-14804](https://issues.redhat.com//browse/OCM-14804)
Specifically, this forces Update to be called when TF attempts to create the HCP global autoscaler. It populates the state as well, so it will only run this once per cluster

OCM-14804 | feat: Allow edit for HCP global autoscaler

---

provider/clusterrosa/classic/cluster_rosa_classic_resource.go

Fixes create/cluster in some situations where the `state`'s version was invalid, now using the `state`'s CurrentVersion
Fixes #[OCM-15886](https://issues.redhat.com//browse/OCM-15886) #924 
**Checklist**

OCM-15886 | fix: Change validateUpgrade versionId to CurrentVersion

---

docs/index.md

There is currently no information on using the `client_id` and `client_secret` parameters when using portal service accounts. This creates confusion when customers are trying to use the access tokens, described at https://docs.redhat.com/en/documentation/red_hat_customer_portal/1/html/creating_and_managing_service_accounts/ref-ciam-svc-acct-api-creating-service-acct, and causes a timeout when provisioning clusters, which is hard-coded at 15 minutes.
**Checklist**

OCM-0000 | docs: (copy2) add documentation for using portal service accounts

---

.github/workflows/check-pull-request.yaml

Fixes `check_pull_request` GitHub action, by giving it the correct ginkgo version
This unblocks tests which rely on this action

OCM-17200 | ci: Fix PR CI to unblock other jobs
